### PR TITLE
Refactoring of the i18n; closes #654

### LINKED ISSUE #654: [1][bigspider] locale/language support seprated among multiple files
If I wanted to remove a language from the drop down, it is not sufficient to remove it from the
`defaults.locale` key, but you would also need to remove it from `IntlStore`
Could the imports be made so that they depend on what the config/settingsstore says, please?

### PR DESCRIPTION
**Pull request by bigspider**
I did some refactoring of the internationalization code, in order to address #654. Summary of changes:

1. Deleted 'assets/locales/locales.js', created instead a list of the locale codes in ''assets/locales.js'; updated 'assets/loader.js' and 'assets/loader-dev.js' to reflect the change and require all the appropriate locale files.
2. Generalized the code in 'stores/IntlStore.js' to use the new list instead of hardcoded locales.
3. Same in 'actions/IntlActions.js'.

While I was there, I also renamed the locale code for Chinese to 'zh' instead of 'cn', which is the ISO 639 and what react-intl expects.

After these changes, adding a new language amounts to: (1) adding the new locale-{xx} file; (2) adding the language the list in 'assets/locales/locales.json'; (3) adding it to the 'defaults' in 'stores/SettingsStore.js', and perhaps (4) possibly add the flag in languages/dropdown.

It would be possible to similarly automate (3) and use the list from 'assets/locales.js', but it's unclear to me if this change would be wanted or the 'defaults' should stay separated to allow customization (for example, to reorder the languages in the dropdown).

### CODE REVIEW

**Comment by svk31** [comment]
For some reason this breaks locale changes for me, on `counterpart.setLocale(locale);` retranslations are triggered for all react-translate components, and somehow a translation is attempted for a key `true`, which is not a string and does not have `split`, which throws an error. I had a quick look but couldn't really figure out why, in a clean incognito window it works.

image

**Comment by bigspider** [comment]
@svk31 That's weird, I tried to look on how counterpart is used but I couldn't find anything that conflicts with my changes. Let me know if you find a way to reproduce it, so I can try to help with it.

I had forgotten to rename the "cn" Chinese help folder to "zh", so I fixed that in another commit; but I doubt this is related to the error you're experiencing.

**Comment by svk31** [comment]
Ok I've figured out why, it's an issue with the keys stored in localstorage still containing a reference to `cn`, I'll merge this PR then make a separate fix for it.

**Comment by bigspider** [comment]
Cool, thanks @svk31!

**Pull request merged**
