### PR TITLE
Add empty cell

### PR DESCRIPTION
**Pull request by fonero-project**
3ab5287fcf

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
What is the issue here? 

Can you name me an account where I can see the wrong visualization live?

**Comment by fonero-project** [comment]
my version "2.0.180912-rc1"

**Comment by sschiessl-bcp** [comment]
Please merge latest develop and name me an account where I can see what's wrong

**Comment by fonero-project** [comment]
nvm install v6
wget https://github.com/bitshares/bitshares-ui/archive/2.0.180926-rc1.tar.gz
tar vxf 2.0.180926-rc1.tar.gz
cd bitshares-ui-blabla
npm install
npm start

goto page

**Comment by svk31** [comment]
Probably also just the wrong node version (too old)

**Comment by sschiessl-bcp** [comment]
@fonero-project 

Please confirm if that solved your issue

**Comment by sschiessl-bcp** [comment]
@fonero-project 

Please re-open if the npm version did not resolve the issue for you

**Pull request closed without merging**
