### PR TITLE
added EVRAZ to getFeaturedMarkets

### PR DESCRIPTION
**Pull request by sergey-ukhanov**
<h2>General</h2>
Closes #[Insert issue number]

[Insert description of what you did, any description how to test or check your changes are welcome]

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [x] Opera
- [x] Firefox
- [x] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [x] Light
- [x] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Please cleanup your PR

**Comment by sergey-ukhanov** [comment]
> Please cleanup your PR

I didn't really understand what I need to do to make you accept this merge request

**Comment by sschiessl-bcp** [comment]
Please have a look and double check what changes you are trying to merge

**Comment by sergey-ukhanov** [comment]
> Please have a look and double check what changes you are trying to merge

@sschiessl-bcp all I did was pull the latest changes from the develop branch of the main repository, and added evraz to getFeaturedMarkets function. 
Could you describe in more detail what I should pay attention to? 
Thank you!

**Comment by sschiessl-bcp** [comment]
You have 101 unchanged files. It seems you have added any and all files without checking the changes you actually made. Please do so

**Comment by sergey-ukhanov** [comment]
> You have 101 unchanged files. It seems you have added any and all files without checking the changes you actually made. Please do so

@sschiessl-bcp Thank you so much!
Sorry for the inattention. Updated pull request

**Comment by sschiessl-bcp** [comment]
How can I confirm you are from EVRAZ team?

**Comment by abitmore** [comment]
@sschiessl-bcp the PR was developed in a repository in https://github.com/evraz-org/ , I guess it's the official one?

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp the PR was developed in a repository in https://github.com/evraz-org/ , I guess it's the official one?

Yes it was, see #3297

**Comment by sergey-ukhanov** [comment]
> How can I confirm you are from EVRAZ team? 

Yes, I'm from EVRAZ team

**Comment by sergey-ukhanov** [comment]
> How can I confirm you are from EVRAZ team? 

PR was sent from https://github.com/evraz-org/ 
I'm from EVRAZ team

**Comment by sschiessl-bcp** [comment]
Can you please rebase, or allow that reviewers edit your PR? I can't merge otherwise.

**Comment by abitmore** [comment]
Due to the last commit "Merge branch 'change-branding-to-evraz' into develop", I think we can not merge this pull request as is. Please cleanup, or create a new pull request from a new branch. Thanks.

**Comment by sschiessl-bcp** [comment]
stale

**Pull request closed without merging**
