### PR TITLE
Reorganizing nodes by provider and adding node.blockbasis.com

### PR DESCRIPTION
**Pull request by RuneStone0**

### CODE REVIEW

**Comment by svk31** [comment]
It's getting crowded so reorganizing is a good idea. However, "Blockbasis - Blockbasis.com" is not a location. We want actual locations to enable people to choose one close to their location. It doesn't need to be superprecise, but include the contintent at least and preferably also the country.

**Comment by abitmore** [comment]
@RuneStone0 
1. please develop on top of latest staging branch. There are much more nodes now, and location info of some has changed.
2. your node provides only one account history entry for one account, which is not suitable for the reference wallet.

**Comment by RuneStone0** [comment]
Hi, node.blockbasis.com points to a load balanced IP address making the physical address less relevant. Would it be better if we did something like this instead:
Load Balanced Node (node.blockbasis.com)
US East Node (us-east1-b.node.blockbasis.com)

**Comment by RuneStone0** [comment]
Thanks for the feedback. I'll make a new pull reqest on latest staging branch and change the node name.

**Pull request closed without merging**
