### PR TITLE
Removing unmatched background from Markets page

### PR DESCRIPTION
**Pull request by AmmarYousefM**

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
How does it look on exchange? (same component reused there)

**Comment by AmmarYousefM** [comment]
> How does it look on exchange? (same component reused there)

Exchange page is matching the theme.

**Comment by ioBanker** [comment]
> How does it look on exchange? (same component reused there)

It looks the same to me:

image

**Comment by sschiessl-bcp** [comment]
Can you post all three themes please?

**Comment by AmmarYousefM** [comment]
> Can you post all three themes please?

market_grey
market_white
market_mid

**Pull request merged**
