### PR TITLE
1407 reconnect strategy

### PR DESCRIPTION
**Pull request by sschiessl-bcp**
Addresses #1353 #1074 #1407

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Strategy was refined to match #1485

Popup currently looks like this, any thoughts?
screenshot_20180702_172638

It disappears if connection recovers

**Comment by sschiessl-bcp** [comment]
Could you please merge this into develop @svk31 @startailcoon ? I'd like to test it in the github deployment.

**Comment by svk31** [comment]
It fails to build because you're missing the ifvisible.js dependency. Also, please stick to the regular import syntax instead of using require.

The text is also a bit awkward, maybe @wmbutler can suggest a replacement?

The button styling needs some fixing too, and the Confirm button could be renamed "Reconnect" or something.

image

**Comment by sschiessl-bcp** [comment]
- Adjusted the popup 
image

- import normalized

- ping node button did not have the same issue
image

**Comment by sschiessl-bcp** [comment]
I created code duplications in App.jsx and Footer.jsx, getBlockTime and getBlockTimeDelta

https://github.com/bitshares/bitshares-ui/blob/4e16ee0e5a8ace367f1b1bbe54f327dc2f740a74/app/components/Layout/Footer.jsx#L164

https://github.com/bitshares/bitshares-ui/blob/4e16ee0e5a8ace367f1b1bbe54f327dc2f740a74/app/App.jsx#L156

I would like to have that in one file but I was unsure where it would fit? It doesn't really belong in a Store, does it? Maybe Actions?

Any thoughts @svk31 @startailcoon

**Pull request merged**
