### PR TITLE
Adding disclaimer link to footer

### PR DESCRIPTION
**Pull request by ioBanker**

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Parking this for now

**Comment by abitmore** [comment]
> Parking this for now

What do it mean? And Why?

**Comment by sschiessl-bcp** [comment]
That was unclear, mostly a note to self. 

I am not convinced yet we need it so prominent. Parked as in: not rejected and not accepted either.

**Comment by sschiessl-bcp** [comment]
@abitmore shall be remove the permanent warning on top replaced by this disclaimer in the footer?

**Comment by abitmore** [comment]
Since the one on the top is configurable, I think it does not prevent this PR from being merged. BTW I think it's good to put something on the top, we can discuss this elsewhere though.

**Pull request merged**
