### PR TITLE
- add RUDEX.PZM, icon and markets

### PR DESCRIPTION
**Pull request by serdrdoor**
- add RUDEX.PZM, icon and markets
- add custom field for public key PZM (for withdrawals)
- change endpoint RuDEX gateApi

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Could you elaborate please on the need for the public key field plz for withdrawals?

The old endpoint for gateway is still live?

**Comment by serdrdoor** [comment]
> Could you elaborate please on the need for the public key field plz for withdrawals?
> 
> The old endpoint for gateway is still live?

Yes - all endpoints are currently supported and operational ..

The public key is needed for output. This is a feature of the blockchain.

The public key is NOT ALWAYS known and can be obtained from the PRIZM blockchain - these are features.
While the account is not activated in the blockchain, information about its public key cannot be obtained, because not available - in this case - the user needs to enter it on his own - the user can find it in his wallet. After activating the account, the public key becomes available for receipt and auto-completion in the corresponding field in DEX UI.

**Comment by sschiessl-bcp** [comment]
Your PR includes a change to the generic WithdrawModal. Would you be able to do do integration tests for all gateways with release candidate?

**Comment by serdrdoor** [comment]
> Your PR includes a change to the generic WithdrawModal. Would you be able to do do integration tests for all gateways with release candidate?

yes, I can check

**Comment by sschiessl-bcp** [comment]
Please rebase onto latest develop

**Pull request merged**
