### PR TITLE
#2696. use fee selection feature on the transaction confirmation

### LINKED ISSUE #2969: Allow "single" change of Fee asset on TX
My own opinion is that it would be nice to have a "change fee asset directly" when yo do a transaction, that doesn't stick to be the default, but just for that one op. But that's for a followup issue I think.

_Originally posted by @startailcoon in https://github.com/bitshares/bitshares-ui/issues/1117#issuecomment-512752150_

With the new Fee selection component we can now let the user select the default fee asset in a nice view. At the moment we have not enabled this feature directly on the Transaction confirmation itself, which would be a nice addition.

Related are https://github.com/bitshares/bitshares-ui/issues/1498

### PR DESCRIPTION
**Pull request by OpenLedgerApp**
<h2>General</h2>
Closes #2969 

Added this feature for all used transaction operations.

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_
for example create asset operation
image

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
What you did here is the very first step of this task: https://github.com/bitshares/bitshares-ui/issues/2975

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/issues/2969#issuecomment-516814740

**Comment by abitmore** [comment]
@OpenLedgerApp please take a screenshot from Barter transaction confirmation page (https://develop.bitshares.org/#/barter)? Thanks. I need the JSON of the whole transaction but not only JSON of individual operations.

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp fixed.
now it looks like:
image
SetDefaultFeeAssetModal is openning when you click on the arrow.
image

**Comment by OpenLedgerApp** [comment]
@abitmore 
image

**Comment by abitmore** [comment]
@OpenLedgerApp thanks. The transaction about proposal is fine, but I wrongly stated my needs. So this is the update: in the first picture, the transaction to cancel multiple orders in a batch, I need a JSON of the whole transaction, but not (only) multiple JSONs for individual operations.

**Comment by sschiessl-bcp** [comment]
> @OpenLedgerApp thanks. The transaction about proposal is fine, but I wrongly stated my needs. So this is the update: in the first picture, the transaction to cancel multiple orders in a batch, I need a JSON of the whole transaction, but not (only) multiple JSONs for individual operations.

The "Show raw json" shows you the tree of the whole transaction. Let's do copyable text in https://github.com/bitshares/bitshares-ui/issues/3020

**Comment by abitmore** [comment]
> The "Show raw json" shows you the tree of the whole transaction.

What I meant is a json of the whole transaction to be signed, but not an operation in the transaction. Current implementation only shows a tree of a single operation. I asked for barter because I made a mistake, thought it would contain multiple operations. Later I asked for "the transaction to cancel multiple orders in a batch" which will contain multiple operations in a transaction.

**Comment by sschiessl-bcp** [comment]
@OpenLedgerApp does it only show assets that are valid in fee pool and user balance to actually pay the tx fee?

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp no, it shows all user balances, like on the settings page

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp no, it shows all user balances, like on the settings page

It should only show asset that can actually be used, in the settings that is fine, but here it would break UX. Please add it to this issue, but please note #3044 first.

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp No, i'm interested in this task, but i will finish it in a few weeks

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp No, i'm interested in this task, but i will finish it in a few weeks

Could you please be a bit more precise in the expected timeline?

**Comment by sschiessl-bcp** [comment]
I assume you have no interest anymore.

**Pull request closed without merging**
