### PR TITLE
Merge the build and the deployment jobs

### LINKED ISSUE #3502: Missing commit hash in generated commit message for web-wallet deployment
**Description**

Starting from https://github.com/bitshares/bitshares-ui/commit/fd99821c3c20e64631d165d6989a35b444fb14bf (after https://github.com/bitshares/bitshares-ui/commit/c19b2d9afc20c1f53e771d5a8d3fcdef6a88455f), the commit hash of the source code is no longer in the generated commit messages for web-wallet deployment.

This is caused by the separation of jobs - there isn't a `checkout` step in the 2nd job, so unable to get the commit hash.

I have a fix in my fork repository: https://github.com/abitmore/bitshares-ui/commit/9681602acf01770d8cb956cb273308da425fa0e1 .

**To Reproduce**
1. Go to https://github.com/bitshares/develop.bitshares.org/commits/master
2. Scroll down

**Expected behavior**
The same behavior as before.

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by abitmore**
Closes #3502.

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
I wanted it to be a seperate job in order to allow preparation of everything beforehand. That allows to inspect binaries if necessary, or run any sort of tests on it before deploying https://github.com/bitshares/bitshares-ui/commit/bc2f1adde262e90aa96c86e5c31e72a193c605ab

The commit message in the deployment repository would then contain the source commit hash. Is that sufficient?

**Comment by abitmore** [comment]
@sschiessl-bcp firstly, I don't like that you force-pushing to the `develop` branch. It may cause unexpected issues due to human errors. It's the best to always update `develop` via pull requests (with the additional benefit that all changes will be included in the auto-generated release notes).

image

And unfortunately your change did not work. Perhaps need to use double brackets `${{ ... }}`?

image

**Comment by abitmore** [comment]
Actually the `git rev-parse` command won't work because there wasn't a `checkout` step in the 2nd job. Otherwise the commit hash will have been added to the message already.

**Comment by abitmore** [comment]
Obsolete due to https://github.com/bitshares/bitshares-ui/commit/0995347eece74ea72a29826ad477efa8aa71d96c.

**Pull request closed without merging**
