### PR TITLE
Closes issue #2093 - Explore Accounts - Styleguide + Sorting Update

### LINKED ISSUE #2093: [10][alexandr-masl] Explore Accounts - Styleguide + Sorting Update
**Describe the bug**
The accounts overview in Explore -> Accounts has no sorting feature. When loading the list the accounts come up in an unorderly fission.

**To Reproduce**
1. Go to Explore
2. Click on Accounts

**Expected behavior**
Sorting possibility by all fields (id, account name, current balance, percent of total supply), and automatic sorting on loading.

**Screenshots**
screenshot from 2018-10-29 09-38-50

**Desktop (please complete the following information):**
1. OS: Win 10
2. Light Wallet
3. Version 181031-RC1

### PR DESCRIPTION
**Pull request by alexandr-masl**
This PR fixes #2093 issue

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
> why at least 2 digits ? I think 1 character is enough to start searching, isn't so ?

Arbitrary number, 1 is fine too.

**Comment by cogutvalera** [comment]
so IMHO just in search field to type prompt something like "Type to search ..." will be enough, isn't so ?

**Comment by sschiessl-bcp** [comment]
> so IMHO just in search field to type prompt something like "Type to search ..." will be enough, isn't so ?

I'd rather have it more prominently in the header, or as fake row in the table. The search field is easy to miss if you don't know it

**Comment by cogutvalera** [comment]
> > so IMHO just in search field to type prompt something like "Type to search ..." will be enough, isn't so ?
> 
> I'd rather have it more prominently in the header, or as fake row in the table. The search field is easy to miss if you don't know it

make sense, thanks !

**Pull request merged**
