### PR TITLE
1437 - Consolidate Wallet Login Types

### PR DESCRIPTION
**Pull request by kapeer42**
Implementation of #1437

Original scenarios [here](https://github.com/bitshares/bitshares-ui/issues/895#issuecomment-378263735)

I think the "key file" semantic is appropriate only in the restoring from backup case. I replaced it with "local wallet".
Also the original scenarios were forcing you to choose to restore from a backup or use the active local wallet only.
Instead of Scenario 2 now there is a dropdown to select the wallet you want to login with.

## Scenario 0

This is when there is no local wallet in the database in local wallet mode.
Really this is scenario 2 in @ahdigital description.

bts_1437_scenario_0

## Scenario 1

Cloud wallet login.

bts_1437_scenario_1

## Scenario 2

When the user selected to restore from a backup.

bts_1437_scenario_2

## Scenario 3

When a local wallet is selected (for restoration (.bin) or already imported (not .bin)).

bts_1437_scenario_3

## Scenario 4

The user created a new local wallet that is not backup up.

bts_1437_scenario_4.

### Scenario 4.2

I chose to remove the "Backup and login" button when the user click on "Don't ask me to back up again"

bts_1437_scenario_4 2

### CODE REVIEW

**Comment by ahdigital** [comment]
In scenario 0, 2, 3, 4 and 4.2 why did you change the terminology used from 'Key file' to local wallet? As far as I understood from the discussion we're trying to move from cloud / local wallet to account name / key file to create a clearer distinction between the two.

In scenario 2 what does the drop down menu 'restore from a back up file (.bin)' do? What are the options here? This didn't appear in the mock ups.

In scenario 4, you show a key file E.g. 'Using ubkd4'. What happens if the user clicks 'Use different wallet' without backing up - Will it be forgotten?

**Comment by kapeer42** [comment]
I changed the terminology because of the distinction I make between a key **file** stored in a folder or the wallets stored in the browser database. Tell me if I should change back.

This answers the two latter questions I think:
peek 2018-04-30 14-18_bts_unbacked_

**Comment by abitmore** [comment]
If there is a "backup and login" button, it should be the default. Actually I recommend that we remove the "login" button which won't perform a backup.

**Comment by abitmore** [comment]
@ahdigital I agree that "key file/account name" login is much clearer than before. However, IMHO the "local/cloud" even "wallet/account model" description should be kept on UI for a long enough period for old users to migrate to new UI easier (to produce less confusion).

**Comment by wmbutler** [comment]
> If there is a "backup and login" button, it should be the default. Actually I recommend that we remove the "login" button which won't perform a backup.

@abitmore just to be certain, are you suggesting that Backup and Login is the default choice? Do you realize that this will download a .bin file every time the user logs in?

If I'm following you, I think you are saying that you always want to see just 1 button:

- Don't ask me to back up is unchecked: Show only the "Backup and Login" button.
- Don't ask me to backup is checked: Show only the "Login" button.

**Comment by wmbutler** [comment]
@kapeer42 your UI strays pretty far from the mockups on all screens with upload controls. Can you spend some time to bring this in line?

**Comment by abitmore** [comment]
@wmbutler I guess UI knows whether the user have downloaded a backup before, and whether need to download a new backup? "backup on login" is not the best UX IMHO, but "backup on wallet/account creation" and "backup on key importation" are.

> you always want to see just 1 button

Yes. And make the one with "backup" as default.

**Comment by wmbutler** [comment]
I think this is fine @abitmore @ahdigital @kapeer42 

Backup and Login displays unless:
- "Don't ask me to back up again" is checked

In which case we display login. I believe we had a 90 day notice to ask the user to backup again. Should we just toggle the checkbox off after 90 days to force the same behavior again?

**Comment by kapeer42** [comment]
@ahdigital About the upload button UI: should I make a new component that mimics the mockup or use the upload components that are in bitshares-ui-style-guide?

**Comment by ahdigital** [comment]
@gibbsfromncis what do you think about upload component. Would the ANT version be ready for integration soon or should kapeer mimic the functionality?

**Comment by kapeer42** [comment]
Current state, will push soon:
## Account name login
account_login
## Into already stored key file login
current_wallet_login
## Into restore backup
restore_from_backup
## Into create new local wallet then backup & login
backup login

**Comment by wmbutler** [comment]
- [ ] css so error notifications don't cause modal heights to jump
- [ ] Smaller font size, particularly for password field, but let's be consistent here.

**Comment by kapeer42** [comment]
Update, still need to clean up a bit before push:
bts_errors_and_sizes

**Comment by kapeer42** [comment]
What should I do about the non-english translation keys that will be missing?

**Comment by svk31** [comment]
Solid work, thanks!

**Pull request merged**
