### PR TITLE
#2938. missing path for locale 'ru'(infinite loops)

### LINKED ISSUE #2938: infinite loops - missing path 'assets/BTS' for locale 'ru' #2789
The issue still not fixed. please reopen ticket

Screen Shot 2019-07-12 at 23 07 25

### PR DESCRIPTION
**Pull request by OpenLedgerApp**
<h2>General</h2>
Closes #2938 

Removed console operations. After cleaning the code this issue was fixed.
I need more time to learn why console operations influenced on infinite loops. It's a hot fix.

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_
image

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
The console logs include several variable renderings. Please check what is going wrong there to find the cause

**Comment by OpenLedgerApp** [comment]
> The console logs include several variable renderings. Please check what is going wrong there to find the cause

`let locale = this.props.locale || counterpart.getLocale() || "en";
        if (!HelpData[locale]) {
            console.log("missing locale help files, rolling back to 'en'");
            locale = "en";
        }

        let value = HelpData[locale][this.props.path];

        if (!value && locale !== "en") {
            console.log("missing path for locale help files, rolling back to 'en'");
            value = HelpData["en"][this.props.path];
        }

        if (!value && this.props.alt_path) {
            console.log("missing path for locale help files, rolling back to alt_path");
            value = HelpData[locale][this.props.alt_path];
        }
`
we have the same result with a such console.logs (without variable renderings).

image

**Comment by sschiessl-bcp** [comment]
Please investigate why the `console.error` break. I don't want to fix a symptom without knowing the cause

**Comment by sschiessl-bcp** [comment]
ping

**Comment by OpenLedgerApp** [comment]
It will take more time than this task has been estimated. It's not an obvious issue.

**Pull request closed without merging**
