### PR TITLE
add new API node

### PR DESCRIPTION
**Pull request by ety001**
add new API node

### CODE REVIEW

**Comment by abitmore** [comment]
Do we need to remove the "liuye.tech" one?

**Comment by ety001** [comment]
@abitmore No. `wss://bts.liuye.tech:4443/ws` is my personal API node and It locates on China. `wss://api.1hour.win/ws` is owned by GBAC and I'am the maintainer of it.

**Comment by sschiessl-bcp** [comment]
What is https://1hour.win/?

**Comment by ety001** [comment]
> What is https://1hour.win/?

Oh, that's a side project which I forget to close.

**Comment by sschiessl-bcp** [comment]
> > What is https://1hour.win/?
> 
> Oh, that's a side project which I forget to close.

It reads like a quite questionable domain for a trusted node. Any chance you could use a bitshares-related one?

**Comment by ety001** [comment]
> > > What is https://1hour.win/?
> > 
> > 
> > Oh, that's a side project which I forget to close.
> 
> It reads like a quite questionable domain for a trusted node. Any chance you could use a bitshares-related one?

I have changed the api node url to `wss://api.gbacenter.org/ws`.

**Comment by sschiessl-bcp** [comment]
Much appreciated

**Pull request merged**
