### PR TITLE
fix appveyor and action bug

### PR DESCRIPTION
**Pull request by xiangxn**
<h2>fix appveyor and action bug</h2>
Fix 'appveyor' and 'action' build failures due to network issues.

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Should the --frozen-lockfile not also remain, plus the concurrency?

**Comment by xiangxn** [comment]
In the case of a fast network, concurrency will cause the installation of dependencies to fail, which is a yarn problem.

**Comment by xiangxn** [comment]
Although upgrading yarn can solve this problem, however, because the project depends on many old packages, upgrading yarn may cause new problems.

**Comment by xiangxn** [comment]
frozen-lockfile can still be preserved, even if it is not preserved, it will work fine.

**Pull request merged**
