### PR TITLE
Issue 1532 - Generated Password Display

### PR DESCRIPTION
**Pull request by startailcoon**
# Fixes Issue #1532 

- Decreased font size for generated password output

### CODE REVIEW

**Comment by abitmore** [comment]
Since it's readonly, can we change it to a `textarea` or simply `div` or `span` or just plain text? No need to use `input` box IMHO.

**Comment by svk31** [comment]
We could, just need to make sure it's styled consistently with the rest of the page.

**Comment by startailcoon** [comment]
I can make a change to the PR in a few days.

**Comment by svk31** [comment]
@startailcoon ping

**Comment by startailcoon** [comment]
give me a few hours. I'll submit it later today

**Pull request merged**
