### PR TITLE
Issue 1525 - Clear Voting Proxy

### PR DESCRIPTION
**Pull request by startailcoon**
# Fixes Issue #1525
Disables Typehead on AccountSelector for proxy voting to allow empty proxy name

### CODE REVIEW

**Comment by abitmore** [comment]
Screenshot please?

**Comment by startailcoon** [comment]
I can fix a screen shot of it later today

**Comment by startailcoon** [comment]
bitshares-voting

**Comment by abitmore** [comment]
Thanks. I don't know if the UX is ideal, but at least the feature is there.

**Comment by startailcoon** [comment]
I agree that the UX needs some work, but I'm not a UX guy. When we have a UX for this I'm happy to put it in, but this was such a priority issue I think we should have this fixed ASAP.

**Pull request merged**
