### PR TITLE
Fix, choosing the default currency.

### PR DESCRIPTION
**Pull request by fonero-project**
Displayed as [object Object]
http://dl4.joxi.net/drive/2018/09/24/0009/3993/593817/17/ad19e3d7d5.png
http://dl3.joxi.net/drive/2018/09/24/0009/3993/593817/17/6942ae782c.png

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Which branch is that error visible? I can't reproduce the [object Object] issue

**Comment by azartpay** [comment]
All versions have this bug. I tried both releases and dev versions.

**Comment by fonero-project** [comment]
All versions have this bug. I tried both releases and dev versions.

**Comment by fonero-project** [comment]
nvm install v6
wget https://github.com/bitshares/bitshares-ui/archive/2.0.180926-rc1.tar.gz
tar vxf 2.0.180926-rc1.tar.gz
cd bitshares-ui-blabla
npm install
npm start

**Comment by svk31** [comment]
You probably just need to use a newer version of node, try v8 or v9

**Comment by sschiessl-bcp** [comment]
@fonero-project 

Please confirm if that solved your issue

**Comment by sschiessl-bcp** [comment]
@fonero-project 

Please re-open if the npm version did not resolve the issue for you

**Pull request closed without merging**
