### PR TITLE
Issue 661, 2803 - Account Membership Stats

### LINKED ISSUE #661: [6] View referrals in wallet
It would be a good tool to view referrals inside the wallet. At the moment we can only do this online at cryptofresh. I see a list of username and date of signup as the minimal task for this.

Additional tasks could be to add a tab in the account activity to also view Referral commissions that you will receive.

I think this would make it more visible for others that you can refer others and earn commission on their transactions.

### LINKED ISSUE #2803: [2] Refine explanation of referral rewards program
image

It's not as self-explanatory as it should be.

### PR DESCRIPTION
**Pull request by startailcoon**
Closes #661 
Closes #2803 

This PR updates the Membership Stats section to also view a table of referred members. This is limited to members that has not upgrade to LTM as they are their own referrers. 

The table is also limited to no sorting and can only load next page after previous is loaded, due to some ES / node limitations at the moment.

#### Changelog

```
+ Query ES for Referrals data
+ Query Node for Referrals details
+ New Component AccountReferralsTable
* Add new ES node
* Statistics also viewable as plainText
- Remove unessesary components
```

### CODE REVIEW

**Comment by startailcoon** [comment]
# New Layout for Membership Stats

## LTM

### Details Section
Screenshot_2019-08-10_20-26-02

### New Referrals List

This list is limited to non sort-able due to the ES query not supporting it yet. Accounts are loaded only for current page to decrease node stress.


Screenshot from 2019-08-10 20-27-10



## Basic Members

Basic members have almost the same layout, except for the information about a lifetime membership and the signup button.

Screenshot_2019-08-10_22-08-36

**Comment by sschiessl-bcp** [comment]
Does this include a proper non-ES fallback?

**Comment by startailcoon** [comment]
> 
> 
> Does this include a proper non-ES fallback?

At the moment it does not. Without the ES we can not retrieve the required data for the list. Currently it only rely on one ES node, which needs to be fixed. If no data can be retrieved it also needs to have a fallback to some information on why.

**Comment by sschiessl-bcp** [comment]
The only thing that we can't do without ES is the distribution, right?

**Comment by startailcoon** [comment]
> 
> 
> The only thing that we can't do without ES is the distribution, right?

ES gives us the referrals by ID, so without ES the table would be empty. I'll have to test what happens if ES is unreachable.

**Comment by startailcoon** [comment]
A failure of the ES node will result in an empty data table as below with the console errors.

Right now this component is fixed to a specific ES node (no 1 in the array) which is the only one that has this enabled. We should rotate and retry on failure for a call. I will work on improvements of ES node usage on issue #1734 

image

image

**Pull request merged**
