### PR TITLE
Fixing header's username not fully appearing

### PR DESCRIPTION
**Pull request by AmmarYousefM**
Before:

before

After:

after

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Which browser / OS have you used to test this?

**Comment by AmmarYousefM** [comment]
> Which browser / OS have you used to test this?

Firefox/Chrome (Latest) over *Windows 10 Pro*

**Comment by sschiessl-bcp** [comment]
I ll play around a bit with it, I'm getting scrollbars here where the name is

**Comment by ioBanker** [comment]
> I ll play around a bit with it, I'm getting scrollbars here where the name is

What browser are you using; I'd tested it over Chrome and Firefox and haven't seen any scrollbars up there.

Perhaps will check if I have that browser and play around it with you 💕

**Comment by abitmore** [comment]
I'm on Ubuntu 18 and latest firefox. I can confirm the old appearance.
image

**Comment by ioBanker** [comment]
> 

I'd found another way to fix it; I am closing this PR and opening another one.

**Pull request closed without merging**
