### PR TITLE
Issue 1379 - Enable Market Picker

### PR DESCRIPTION
**Pull request by startailcoon**
# Fixes Issue #1379 
- Add gateAssets=true/false for list_assets
- Update Translation
- Update SSCS
- Call getAssetList for 25 records (be kind to servers)
- Callback for onShowMarketPicker
- Include AssetStore on Exchange
- New Icons (filter, info-cicle-o, zoom)

bitshares-marketpicker_4

### CODE REVIEW

**Comment by svk31** [comment]
This looks good, but can you please refactor the market picker code into a new component MarketPicker instead of including it directly in Exchange.jsx?

**Comment by startailcoon** [comment]
I'll make the changes to the PR later today.

**Comment by wmbutler** [comment]
Bug report

When attempting to insert a letter into the Asset field (lower case), the cursor jumps to the end of the field. This does not happen when holding down the shift key while typing the letter. Possibly has something to do with the uppercase substitution?

picker

**Comment by startailcoon** [comment]
I'll commit an update for this issue tomorrow

**Comment by startailcoon** [comment]
Case Sensitive issue has been fixed.
Input is not replaced with toUpperCase, while the value to find is still uppercase.

**Pull request merged**
