### PR TITLE
Removed comma in Exchange header

### PR DESCRIPTION
**Pull request by freak5g**
This one:
Screenshot from 2021-07-20 18-30-33

The above image is also a proposition  to make those tooltips unintrusive, preferably on click.

Screenshot from 2021-07-20 18-33-30

Screenshot from 2021-07-20 18-59-39

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
For your suggestion, please open a separate issue.

**Comment by sschiessl-bcp** [comment]
For your PR, please show a screen of what you have changed. The old label explorer.block.call_limit had a variable, yours does not.

**Comment by freak5g** [comment]
In short this translation was shared.

I've created new label exchange.call_limit.
explorer.block.call_limit is used by depth chart on collateral markets and not only I guess, so I didn't touch that (with some  cosmetic exceptions).
I took exchange.feed_price independency as example.

Screenshot from 2021-07-21 15-40-11
Screenshot from 2021-07-21 16-11-31

**Comment by sschiessl-bcp** [comment]
Had errors on opening, please check and reopen if still desired

**Pull request closed without merging**
