### PR TITLE
[Showcases] Barter with optional escrow

### LINKED ISSUE #1859: [Showcases] Escrowed transfer, or off-the-book trade
<h1>Showing the strength of the blockchain</h1>
It happens quite often in telegram channel that people look for approaches how to solve their task, and quite often it happens that the existing features can already help to realize it. The reference UI should show the strength of the blockchain, and currently it mostly leverages the exchange. The showcases intend to open new possibilities. 

<h2>Escrowed transfer, or off-the-book trade</h2>
A simple escrowed transfer can be realized between two parties and an optional appointed escrow with a proposal. Let's assume account A and B, and E (escrow). The proposal contains now

- transfer of asset X from A to B
- transfer of asset Y from B to A
- optional with escrow:
  - transfer of marginal amount of BTS from E to A or B
  - transfer of approval and transfer fee plus escrow fee in BTS from A or B to E

<h3>Specification</h3>
User must be able to

- see a descriptive text that explains the leveraging of the proposal system and the fee breakdown (propose, approval and transfer fee)
- enter account A and B as well as asset and amount of X and Y
- optional with escrow: enter account E and escrow fee in BTS

<h3>Tasks</h3>

- [x] Create mockup and tile for #1857 
- [x] Implement design
- [x] Implement business logic

This issue is also for discussion and feedback collection and part of #1857

### PR DESCRIPTION
**Pull request by sschiessl-bcp**
Closes #1859 

Adds the Barter feature. Comes with following features:
 - init screen
image

- barter between two accounts
image
image

 - barter using escrow as witness, with escrow payment
image
image

 - barter using escrow as custodian, with escrow payment
image
image

- barter using escrow as custodian, no escrow payment
image
image

Furthermore:
- ApplicationApi was refactored (to enable transfer_list)
- Fully responsive UI and wizard like middle element
- Tooltips throughout for explanation

This was a joint development from Alex and I. Total hours needed: 27

### CODE REVIEW

**Comment by CryptoKong** [comment]
This is really cool, could there be a way to stop scammers proposing tx to swap a useless uia for someones entire portfolio etc. Be quite disheartening if a noob accepts such a proposition without realising whats going on.

**Comment by sschiessl-bcp** [comment]
Proposals from suspected scammers can only be accepted with a double confirm.

In general I'm not sure you can come up with a metric that would identify such a proposal if not from those accounts

**Comment by CryptoKong** [comment]
Well, im glad its been considered at least. Good work 👍

**Comment by bitfanatic** [comment]
Its looking very cool

Would be nice to have ability to memo for escrow account 

And maybe memo under each asset so its possible to trade other things than crypto currencies

**Comment by sschiessl-bcp** [comment]
> Its looking very cool
> 
> Would be nice to have ability to memo for escrow account
> 
> And maybe memo under each asset so its possible to trade other things than crypto currencies

Indeed a valid request. I could imagine that every "amount" selector gets a "add memo" button in the header. Please open a new issue for that, since it wont make it in this PR

**Comment by sschiessl-bcp** [comment]
There will also be an overview of barter proposals in that component, just not yet. So far they will appear in dashboard

**Comment by bitfanatic** [comment]
I have tried adding an issue about my earlier comment as u requested 

Not sure how to label it as enhancement 

But hope its to standard

**Comment by grctest** [comment]
>@CryptoKong: "could there be a way to stop scammers proposing tx"

If you had to accept a barter initiation request before the other user could propose terms for the barter/trade, then that could reduce the likelihood of somehow accidentally trading away all your tokens?

**Comment by bitfanatic** [comment]
> This is really cool, could there be a way to stop scammers proposing tx to swap a useless uia for someones entire portfolio etc. Be quite disheartening if a noob accepts such a proposition without realising whats going on.

A summary box that states how much u gain or lose on the trade i think would do the trick 

compared to realtime price of the assets at the time of the proposal 

And function to stop incoming barter proposal from certain accounts 
Know scam accounts and accounts that spams u with proposals

**Comment by sschiessl-bcp** [comment]
> A summary box that states how much u gain or lose on the trade i think would do the trick

You see all the transfers in the proposal

> compared to realtime price of the assets at the time of the proposal

Prices, especially for scam assets, are easily manipulated. Rather not give a false sense of security here

> Know scam accounts and accounts that spams u with proposals

That function already exists, proposal from known scammers / spammers can't be approved without request

**Comment by bitfanatic** [comment]
> > A summary box that states how much u gain or lose on the trade i think would do the trick
> 
> You see all the transfers in the proposal
> 
> > compared to realtime price of the assets at the time of the proposal
> 
> Prices, especially for scam assets, are easily manipulated. Rather not give a false sense of security here
> 
> > Know scam accounts and accounts that spams u with proposals
> 
> That function already exists, proposal from known scammers / spammers can't be approved without request

Good point about the scam assets would be to easy to manipulate and give a false sense of security

**Pull request merged**
