### PR TITLE
LP staking (A determine B and B determine A)

### LINKED ISSUE #3546: Adding liquidity pool feature request
https://wallet.bitshares.org/#/pools

As a user, when adding a liquidity pool, I hope that when A is determined, B will also be determined.

image

### PR DESCRIPTION
**Pull request by ioBanker**
Closes #3546

### CODE REVIEW

**Review by abitmore — COMMENTED** [review]
Terrible code formatting :P

**Comment by ioBanker** [comment]
I know I am a horrible street coder; perhaps you and @sschiessl-bcp can forgive me 🙈 please help with formatting

**Comment by ioBanker** [comment]
Thanks for the formatting; I believe the change is working fine as we'd tested it for the past 3 days massively.

**Comment by sschiessl-bcp** [comment]
Tested another edge case, seems fine

**Pull request merged**
