### PR TITLE
#1503 Scaled Orders

### LINKED ISSUE #1503: [UX+UI:28][gibbsfromncis] Modal for Scaled Orders
As a trader I would like to be able to add scaled orders in the similar way to bitfinex

image

image

### PR DESCRIPTION
**Pull request by gibbsfromncis**
Closes #1503
 
Screenshots:
screenshot 2018-12-12 05 13 57
screenshot 2018-12-12 05 13 47
screenshot 2018-12-12 05 13 32

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
In Chrome
image

**Comment by sschiessl-bcp** [comment]
Is it possible to allow scrolling while the Scaled Orders tab is open? Then user can scroll down to Order book. 

Additionally, maybe show current spread (high and low) prices in the tab.

**Comment by sschiessl-bcp** [comment]
This message is confusing
image

I assume this means I have no balance?

**Comment by sschiessl-bcp** [comment]
I clicked on "Scaled Orders" in the tab "Sell BTS". But the Quantity in the Scaled Orders is to be given in bitUSD, is that on purpose?

**Comment by gibbsfromncis** [comment]
> In Chrome
> image

I do not see it in my browser:

screenshot 2019-02-21 01 20 25

> Is it possible to allow scrolling while the Scaled Orders tab is open? Then user can scroll down to Order book.

Unfortunately, I didn't find a way to make it possible. I've tried but no luck...

> I assume this means I have no balance?

You're right. Fixed.

screenshot 2019-02-21 02 24 28

> I clicked on "Scaled Orders" in the tab "Sell BTS". But the Quantity in the Scaled Orders is to be given in bitUSD, is that on purpose? I'd expect the Quantity to be the same as in the "Sell BTS" tab.

You're right. Fixed.

screenshot 2019-02-21 02 25 49

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp will you have a time to review it?

**Comment by sschiessl-bcp** [comment]
image

This still happens, on Chromium + ArchLinux. On click does not open the tab from the side anymore (did a fresh npm install and cleared cache)

**Comment by gibbsfromncis** [comment]
Solution for not logged in users:

screenshot 2019-02-26 10 06 53

UX improvements task: #2497

**Comment by sschiessl-bcp** [comment]
Merging this and moving the further review to the UX issue, as requested by gibbs

**Pull request merged**
