### PR TITLE
#2589 htlc support

### PR DESCRIPTION
**Pull request by dot5enko**
#2589 work in progress. added htlc helper to create, redeem and extend these op

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Is this completed?

**Comment by dot5enko** [comment]
@sschiessl-bcp not yet

**Comment by sschiessl-bcp** [comment]
What's missing and what's eta? :)

Am 27. April 2019 12:31:16 nachm. schrieb dot5enko <notifications@github.com>:

**Comment by dot5enko** [comment]
i'm having some troubles testing bitsharesjs 3.0.0-rc1 cause its not in npm's repo

**Comment by sschiessl-bcp** [comment]
Delete the installed version you have and install with npm install x 
directly, where x is a link to the respective github commit, see the 
package.json for examples

Am 28. April 2019 1:56:31 nachm. schrieb dot5enko <notifications@github.com>:

**Pull request merged**
