### PR TITLE
2655 - InOrders Column on the Portfolio Table 

### LINKED ISSUE #2655: [3][Keegan-lee] Portfolio Columns improvements
**Is your feature request related to a problem? Please describe.**
Inspired by https://github.com/bitshares/bitshares-ui/issues/2140#issuecomment-489259913, we can have "in orders", "in collateral", "in vesting balances" columns in portfolio table.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Keegan-lee**
<h2>General</h2>
Closes #2655

- Add inOrders column to portfolio table
- Add inOrders column sorting to portfolio header

Screen Shot 2019-05-15 at 12 03 04 AM

### CODE REVIEW

**Comment by Keegan-lee** [comment]
This is what the latest collateral and vesting columns look like.

Screen Shot 2019-05-30 at 5 59 03 PM

**Comment by startailcoon** [comment]
> 
> 
> This is what the latest collateral and vesting columns look like.
> 
> Screen Shot 2019-05-30 at 5 59 03 PM

There's really no need to append the asset name on each of these columns once more.

**Comment by Keegan-lee** [comment]
> > This is what the latest collateral and vesting columns look like.
> > Screen Shot 2019-05-30 at 5 59 03 PM
> 
> There's really no need to append the asset name on each of these columns once more.

Oh I know what you mean. I'll make that change.

**Comment by sschiessl-bcp** [comment]
Oh man, this `refs` sorting is da bomb, not. Refactoring to proper render use

**Comment by abitmore** [comment]
https://github.com/bitshares/bitshares-ui/issues/3071

**Comment by sschiessl-bcp** [comment]
Thanks @abitmore !

**Pull request merged**
