### PR TITLE
Create disclaimer.md

### PR DESCRIPTION
**Pull request by ioBanker**

### CODE REVIEW

**Comment by ioBanker** [comment]
It will look like this:

image

image

**Comment by sschiessl-bcp** [comment]
We discussed this in TG a bit, and the latest changes come inspired by https://bitcoin.org/en/legal#information

**Comment by sschiessl-bcp** [comment]
@abitmore @dls-cipher any thoughts?

**Review by abitmore — COMMENTED** [review]
> @sschiessl-bcp
[remove overhead that belongs in readme](https://github.com/bitshares/bitshares-ui/pull/3543/commits/8018a2e93c8ad812e467ab19089d7fc729c12595)

Do we have a link in the wallet to show the contents? If not, I think we need one. Contents in readme does not show in the wallet though.

**Comment by sschiessl-bcp** [comment]
@ioBanker can you please add the disclaimer as first item in the left menu when help is open?

**Comment by ioBanker** [comment]
It's there already in footer; check the print screens, it will stay in footer all the time, I doubt it's needed in help menu.

**Comment by ioBanker** [comment]
The pull request of the link: https://github.com/bitshares/bitshares-ui/pull/3543

**Comment by ioBanker** [comment]
#3557 #3556

**Review by abitmore — COMMENTED** [review]
@ioBanker please close the new pull requests and make the changes in this PR. Thanks.

**Pull request merged**
