### PR TITLE
Add the packaging metadata to build the bitshares-ui snap

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
Hello,

I am working on snapcraft, the new packaging format proposed by Ubuntu to allow developers deliver continuously their software to users without maintainers as intermediaries. You can read more about it here: https://snapcraft.io/

To try this, in Ubuntu 16.04:

    $ sudo apt install snapcraft git
    $ git clone https://github.com/elopio/bitshares-ui
    $ cd bitshares-ui
    $ snapcraft
    $ sudo snap install *.snap --dangerous

(`--dangerous` because the snap the you build doesn't come signed from the store. Once you push it to the store, your users will just have to do $ sudo snap install bitshares-ui)

With this simple file you can easily get your software into the Ubuntu store and expose it to all our users. We are actively developing snapcraft, and I'm particularly interested in blockchain projects because they need a lot of security and they are advancing rapidly. Both things are lacking on the old deb packaging system, and are part our main goals. 

So, I think you could find many more users by publishing the snap, I think that our users would like it very much, and for us any feedback you can give us will be very valuable to define our next priorities.

If you have any questions or comments, please let me know.

**Comment by svk31** [comment]
Hey, that sounds very interesting indeed, I'll check it out.

If I'm reading your commit right, the snap you've created builds the html/js then launches an http server?

Would it be possible to also create a snap that builds the full electron light wallet? (`npm run electron` in `/web/` followed by `npm run release` in `/electron/

**Comment by elopio** [comment]
Hey @svk31, thanks for reviewing!
You are right, this just launches the server. As this is a daemon, it is autostarted when the snap is installed, so you can just open your browser to localhost:8080 to see it running.

It is possible to snap the electron client, sure. Basically, snaps are flexible enough to let you do whatever you want. I don't know much about electron, but I will give it a try.

What would you say if we have a live chat? We can jump into a hangout or something to answer any of your remaining questions, and discuss how snapcraft can fit into your development process.

**Comment by svk31** [comment]
Sure, send me an email at bitsharesblocks@gmail.com and we can discuss it further.

**Comment by elopio** [comment]
@svk31 I sent the email, but got no reply.

**Comment by elopio** [comment]
ping @svk31. I'm checking on old discussions, and I'm wondering if you are still interested in publishing this in the Ubuntu store. 
We recently got a few interesting blockchain snaps into the store, like nanowallet, bitcoin, solidity, parity... and they are getting some nice download stats. You can check the snaps that are already in the store at https://uappexplorer.com/snaps

**Comment by ThomasFreedman** [comment]
I hope you devs are following up on this, as it is a great way to gain more visibility of BitShares to a very wide audience, certainly wider than the crypto-sphere.

**Comment by wmbutler** [comment]
I like this idea. @svk31 if you'd like to estimate this upward to account for time required to review, please do so.

**Comment by happyconcepts** [comment]
Bionic Beaver uses snap (in the Ubuntu app store). It is time!

**Comment by svk31** [comment]
I've added snap builds using electron, but have yet to figure out how to enable automatic uploads. I'll close this PR anyway since we now have snaps available here: https://snapcraft.io/bitshares2-light

**Pull request closed without merging**
