### PR TITLE
Issue 1475 - Adding CR Input Field

### PR DESCRIPTION
**Pull request by startailcoon**
# Fixes Issue #1475 
Adds CR Input Field for manual precision input.

bitshares-cr_input_2

### CODE REVIEW

**Comment by abitmore** [comment]
Good job.

Sometimes I want to lock collateral input. Say, specify how many collateral I would like to put, when changing collateral ratio, debt will change accordingly. So I can know how much debt I can borrow when adjusting CR. Perhaps need to create another issue for this?

**Comment by startailcoon** [comment]
Thanks @abitmore 

Not sure I'm following you with what you mean about "locking collateral input". I guess you mean that you always wish to have a predefined default value, like 3. I think it's worthy of a issue of its own to discuss a good implementation of it.

**Comment by abitmore** [comment]
I mean an (optional) way to: when dragging the bar, change debt amount but not collateral amount.

**Comment by startailcoon** [comment]
Oh, then I understand what you mean.

Maybe we can add a "lock" symbol to lock the collateral amount and let the debt amount be the changing party instead.

**Comment by abitmore** [comment]
I think it's better to create a new issue as well.

**Pull request merged**
