### PR TITLE
Closes #1380 - Messages after socket disconnect

### LINKED ISSUE #1380: [1] Messages after socket disconnect
- [ ] Either stop checking the get_ticker Array or reconnect to the socket.

```
!!! GrapheneApi error:  get_ticker Array(2) Error: websocket state error:3
    at e.call (app.js:11)
    at e.exec (app.js:11)
    at app.js:11
    at t.h (app.js:11) {}
app.js:11 getMarketStats error: Error: websocket state error:3
    at e.call (app.js:11)
    at e.exec (app.js:11)
    at app.js:11
    at t.h (app.js:11)
app.js:11 !!! GrapheneApi error:  get_ticker Array(2) Error: websocket state error:3
    at e.call (app.js:11)
    at e.exec (app.js:11)
    at app.js:11
    at t.h (app.js:11) {}
app.js:11 getMarketStats error: Error: websocket state error:3
    at e.call (app.js:11)
    at e.exec (app.js:11)
    at app.js:11
    at t.h (app.js:11)
app.js:11 !!! GrapheneApi error:  get_ticker Array(2) Error: websocket state error:3
    at e.call (app.js:11)
    at e.exec (app.js:11)
    at app.js:11
    at t.h (app.js:11) {}
app.js:11 getMarketStats error: Error: websocket state error:3
    at e.call (app.js:11)
    at e.exec (app.js:11)
    at app.js:11
    at t.h (app.js:11)
app.js:11 !!! GrapheneApi error:  get_ticker Array(2) Error: websocket state error:3
    at e.call (app.js:11)
    at e.exec (app.js:11)
    at app.js:11
    at t.h (app.js:11) {}
app.js:11 getMarketStats error: Error: websocket state error:3
    at e.call (app.js:11)
    at e.exec (app.js:11)
    at app.js:11
    at t.h (app.js:11)
```

### PR DESCRIPTION
**Pull request by sschiessl-bcp**
Closes #1380, similar approach might be possible for #1346

### CODE REVIEW

**Comment by svk31** [comment]
I'm not sure this will be necessary after merging https://github.com/bitshares/bitsharesjs-ws/pull/15, will have to check that out first.

**Comment by sschiessl-bcp** [comment]
Possible, but it doesn't hurt to have exception handling in place and no code repetition

**Comment by sschiessl-bcp** [comment]
Did you see the error again? Nevertheless, I think that simply removing duplicate code and centralizing the function is worth merging.

**Comment by sschiessl-bcp** [comment]
I am working on Reconnect strategy and testing different scenarios.

I noticed that this happened
image

**Comment by svk31** [comment]
Yea I've seen that too recently, on app init. Might be related to some recent changes in bitsharesjs-ws or routerTransition

**Comment by svk31** [comment]
I ended up going down a serious rabbit-hole when merging this PR. I started refactoring the code slightly to handle clearing the intervals in a central location (marketsActions), but then I started looking at getMarketStats directly and trying to improve the performance. Since I started doing this before actually finishing the merge of develop into your branch it got a little messy and hard to extricate my changes from yours, so everything just went into one merge commit in the end.

End result, I added a queuing system for get_ticker calls that reduces load, and I added storage/retrieval of allMarketStats to MarketsStore, which helps initial rendering of portfolio and market lists. This affects #1643, I was unable to view bill's account before doing this, it still freezes a while but does not crash.

**Pull request merged**
