### PR TITLE
Make bridge withdrawals based on mapping data

### PR DESCRIPTION
**Pull request by motrebski**
<h2>General</h2>

Blocktrades bridge has functionality in wich users can do withdrawals. Memo information is now based on data which are getting from new mapping API call.

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [x] Firefox
- [ ] Safari

There were not changes in UI.

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Is the current implementation still working?

What is the purpose of the new mapping data?

**Comment by dnotestein** [comment]
For the bitshares bridge, we use to use a memo system like "btc:my_receive_address". Now the memo is a UUID. I forget all the reasons for the change, but it's something we want.

**Comment by sschiessl-bcp** [comment]
Merged, only affects Blocktrades. 

If you want or can, I would be interested in hearing the reasons behind the change @dnotestein

**Comment by sschiessl-bcp** [comment]
The release candidate is out, could you please test your integration? #3251

**Pull request merged**
