### PR TITLE
Fix a bunch of UI padding issues

### LINKED ISSUE #254: [4][hyper-bola] Alignment and spacing fixes
Light Wallet latest version

Issued Assets > Update Assets

Here's the normal view:

here's the wrong alignment

### PR DESCRIPTION
**Pull request by hyper-bola**
Changes:

Left justify the main body block ([from here](https://github.com/bitshares/bitshares-ui/issues/254#issuecomment-322764255)) which improved the experience in wide screens.
Fixed a bunch of UI margin/padding issues, cleaned up some hard coded CSS. Fixed #254.

---

Details:

Fixed #254:

image

Other UI padding issue screenshots (which have been fixed in this PR):

1. Extra spacing: 

image

2. Wrong hovering highlighting area:

image

3. Misaligned label:

image

4. No spacing between the input and button:

image

### CODE REVIEW

**Comment by wmbutler** [comment]
Holy crap! What initiative. Thanks. If you can give me a time estimate on this, I'd be happy to award a bounty. There was at least one bounty outstanding on an alignment issue that you appear to have resolved. #254

**Comment by hyper-bola** [comment]
@wmbutler Thank you for your quick response and bounty. I spent about 2 hours on these problems. 

Also I think there may be more problems about layouts, and the style code is not clear enough to be maintained. I'd like to help improving them, and will file another PR later :)

**Comment by wmbutler** [comment]
Absolutely... how are your UI skills aside from alignment. Would love to see some of your work if you are a skilled front end dev. Maybe hit me up on Telegram @billbutler.

**Comment by svk31** [comment]
I thought this was fine at first but when I started looking through the pages I see some weird behaviour. For one I personally am not a fan of left aligning everything, it looks weird to me.

image


Secondly, the 800px max width for the grid-container is far too low for big screens like mine, see screenshot below for example:

image
 
Thirdly, grid-container is a global foundation class, it's not a good idea to override it like that.

**Comment by hyper-bola** [comment]
Thank you for your feedbacks!

Yes I agree that left aligning looks weird sometimes, especially on big
screens.

For different screen widths, we definitely need a more clear, globally
defined layout design spec. Like when to left align the main block and when
to center it, etc. And make the UI responsive in different scenarios (wide,
normal and mobile screens). I'd like to think about it and discuss with you
guys later :)

**Comment by wmbutler** [comment]
I think it's better than the alternative of centering the entire block. Ultimately, the table width should probably flex to allow contents to be displayed in expanded form. Maybe you can allow the table to flex greater than the 800 px limitation as a concession to get this pushed through @hyper-bola ?

**Pull request merged**
