### PR TITLE
Add SMOKE Asset

### PR DESCRIPTION
**Pull request by smokenetwork**
Could you please accept this pull request which adds SMOKE asset to dashboard and markets list?

(request from Smoke.Network)

### CODE REVIEW

**Comment by svk31** [comment]
Can I get some information about this asset please?

**Comment by smokenetwork** [comment]
Sure... 

SMOKE is the cryptocurrency of the Smoke.Network. The first cannabis community to combine blockchain technology with social networking to build a platform that rewards users for posting and curating strain reviews as well as rewards commitment to the network. The Smoke.Network contract initialized on EOS will take a snapshot of all BTS accounts holding SMOKE. SEE HTTPS://SMOKE.NETWORK FOR MORE INFO...  

Fuzzy (One of our largest backers) suggested we create this pull request.

**Comment by svk31** [comment]
Please change the PR target to `staging` instead of master.

**Comment by smokenetwork** [comment]
Done.

**Pull request merged**
