### PR TITLE
#1997 New Sign In / Sign Up styling

### LINKED ISSUE #1997: [11][gibbsfromncis] New Sign Up/Login style-guide integration
This is task was a part of #1832 but moved to separate task

### PR DESCRIPTION
**Pull request by gibbsfromncis**
Closes #1997 

Screenshots: https://github.com/bitshares/bitshares-ui/issues/1997#issuecomment-441342066

I've added some new components (StyleGuide suffix) but I didn't extend all features from original components (only needed features). We will extend these components when continue our styling on other parts of our app.

@sschiessl-bcp Please test all well and let me know is it ready to replace our current Sign In / Sign Up or come back with a list of fixes request :)

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Browsing to login
image

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp good catch. I'll take a look today.

**Comment by sschiessl-bcp** [comment]
Status?

**Comment by sschiessl-bcp** [comment]
> but I didn't extend all features from original components (only needed features)

Also, what did you remove here feature wise?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp Can I ask you please to clarify what do you mean?

**Comment by sschiessl-bcp** [comment]
"but I didn't extend all features from original components"

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp everything what we don't need for signup. For e.g. hide/show password.

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp I missed this fix from my todo list. Sorry

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp pushed. I fixed double usage of `<form>` but ref error I suppose you have because didn't use the latest updates of style-guide. Please make sure you did `npm install` if you catch ref error again.

**Comment by sschiessl-bcp** [comment]
Deleted modeles. /login fires up, when trying to switch the focus to the other login type, this happens
image

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp What do you mean about "deleted modeles" ?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp fixed. We will close this PR today :)

**Comment by sschiessl-bcp** [comment]
- when loggin in with .bin file, the forwarding doesn't work anymore. It just stays on /login route. cloud login still forwards

**Pull request merged**
