### PR TITLE
#2816 Exchange UI/UX Upgrade

### LINKED ISSUE #2816: Exchange UI/UX Upgrade
**Is your feature request related to a problem? Please describe.**
The problem is that the Exchange Tab is highly inconvenient, especially scroll can't be used, the UX is very bad because of that.
**Describe the solution you'd like**
I suggest making the Exchange UI the same as on Binance (Advanced View). I will take care of the implementation

**Describe alternatives you've considered**
I have considered updating the UI of the Exchange Tab anyway.

**Additional context**
From this
Screen Shot 2019-06-22 at 23 03 41
To this 
Screen Shot 2019-06-22 at 23 05 21

### PR DESCRIPTION
**Pull request by MindfulMe**
<h2>General</h2>
Closes #2816

We are making the Exchange UI the same as on Binance (Advanced View). We will take care of further implementation & any fixes.

The problem is that the Exchange Tab is highly inconvenient, especially scroll can't be used, the UX is very bad because of that.

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self-explanatory or documented
- [x] All written text is properly translated (English language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [x] Opera
- [x] Firefox
- [x] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [x] Light
- [x] Midnight

_Please provide screenshots/licecap of your changes below_
Screen Shot 2019-08-08 at 12 54 10

Screen Shot 2019-07-09 at 19 27 56
Screen Shot 2019-08-01 at 13 14 17

### CODE REVIEW

**Comment by MindfulMe** [comment]
Work still in progress, this is just the first day of the development

**Comment by MindfulMe** [comment]
I am eventually merging this one to bts ui exchange tabScreen Shot 2019-07-10 at 10 31 47

**Comment by MindfulMe** [comment]
Preview of the Updated Exchange Tab, all components are operational here Screen Shot 2019-07-19 at 08 46 32

**Comment by MindfulMe** [comment]
Can we do some discussion at the point? The Exchange Tab is already way more convenient for users and overall looks betterScreen Shot 2019-07-20 at 10 48 52

**Comment by startailcoon** [comment]
@MindfulMe nice there, looks really cool. Let us check it out to test it. Can you try to clean up the PR a little, you have a bunch of charting_library files submitted, among other things.

**Comment by MindfulMe** [comment]
@startailcoon take a look at the demo of the changes https://taygete.meta-exchange.info/

**Comment by MindfulMe** [comment]
I will do some cleaning and resolve all conflicts between files tomorrow

**Comment by startailcoon** [comment]
At first glance it doesn't do well on anything less than 1500px and below 800px it's not working at all. You've also removed the personalize modal, and market selector, which is quite important in my opinion.  Not a fan of the independent scrolling order books, and I also really don't see why my open orders need to take up a quarter of the screen.

**Comment by MindfulMe** [comment]
Yeah, surely needs some improvements

**Comment by MindfulMe** [comment]
Removed components can be restructured to match the current changes

**Comment by MindfulMe** [comment]
Anyway, good to have your opinion at the point

**Comment by MindfulMe** [comment]
@startailcoon I have fully updated the responsiveness, now it is fully okay on screens smaller than 1500px

**Comment by MindfulMe** [comment]
Now I will return all of the stuff I removed, including personalize modal

**Comment by sschiessl-bcp** [comment]
IMO we can iterate on the personalize and market picker after finishing with UI

**Comment by MindfulMe** [comment]
I will put "Find Markets" and "Favorite Markets" along with "My Trades" in here
Screen Shot 2019-07-22 at 15 25 28

**Comment by MindfulMe** [comment]
> I will put "Find Markets" and "Favorite Markets" along with "My Trades" in here
> Screen Shot 2019-07-22 at 15 25 28

As tabs

**Comment by MindfulMe** [comment]
Some updates, only need to return the find & favorite markets and that is it - it is fully responsiveScreen Shot 2019-08-01 at 13 14 17

**Comment by MindfulMe** [comment]
imo, it is already looks better and has better ux than current production ui

**Comment by MindfulMe** [comment]
Right panel works againScreen Shot 2019-08-01 at 16 32 19

**Comment by MindfulMe** [comment]
Updated preview is available here -> https://taygete.meta-exchange.info

**Comment by startailcoon** [comment]
Looks like some good changes and progress. With some more polishing we could look on integrating this.

**Comment by MindfulMe** [comment]
Merge conflicts resolved, feel free to provide any suggestions since I have no more ideas what else can be polished

**Comment by MindfulMe** [comment]
@startailcoon

**Comment by MindfulMe** [comment]
http://taygete.meta-exchange.info always contains the up to date version of my commits

**Comment by sschiessl-bcp** [comment]
image

Something seems off in prices of the order book here?

**Comment by MindfulMe** [comment]
@sschiessl-bcp should I remove scrolling & add the current price?
Screen Shot 2019-08-13 at 11 45 57

**Comment by sschiessl-bcp** [comment]
249 and 23 are the prices in my picture I am confused about

**Comment by MindfulMe** [comment]
Okay, yeah I see - I must check it out, the columns might be confused...

**Comment by MindfulMe** [comment]
+ need to fix the padding on the depth chart

**Comment by MindfulMe** [comment]
@startailcoon @sschiessl-bcp I have fixed the bugs, take a look at the latest demo [here](https://exchange.lampgram.com/#/market/USD_BTS). Let us merge it finally to Bitshares-UI and let me know whether I am eligible for some reward.

**Comment by MindfulMe** [comment]
It is fucked up in Safari and on Firefox

**Comment by MindfulMe** [comment]
Yeah, I have fixed them already though not there, I think I have no time for the iteration (to merge changes to current PR branch)

**Comment by sschiessl-bcp** [comment]
Can the end result be seen somewhere?

**Pull request closed without merging**
