### PR TITLE
#1927 - ANT Replacement for AssetSelector

### LINKED ISSUE #1927: [6][kapeer42][1][gibbsfromncis] ANT Replacement for Asset Selector
Replace `Asset Selector` dropdown with ANT components.

Example issue #1872 

image

### PR DESCRIPTION
**Pull request by kapeer42**
Closes #1927 

It's mostly a drop-in replacement for the old one.

If you want to test what's in the screenshots see [this branch](https://github.com/kapeer42/bitshares-ui/tree/1927_demo), this PR only contains the component addition, not the integration (a9011a48657f0fe1f1b3678175c7810427a5353b).

asset-selector-asset-update-demo asset-selector-deposit-demo asset-selector-find-markets-demo asset-selector-amount-selector-demo

### CODE REVIEW

**Comment by gibbsfromncis** [comment]
@kapeer42 I did review of your demo and I have the following question:

screenshot 2018-10-31 23 08 48

- What is the idea of this "clear" (X) button on Withdraw modal?
- To be honest I cannot even type anything on this asset selector

**Comment by kapeer42** [comment]
@gibbsfromncis 
> What is the idea of this "clear" (X) button on Withdraw modal?

It's the validation status of the input. If the asset name you entered is valid it's a valid symbol, if not it's a cross.

**Comment by kapeer42** [comment]
@gibbsfromncis I have updated the demo branch with the new commit, what you showed in the screenshot should have been resolved.

**Comment by gibbsfromncis** [comment]
@kapeer42 Please use features we have already built in our style-guide - https://ant.design/components/form/#components-form-demo-validate-static to display the status of selected asset

**Comment by sschiessl-bcp** [comment]
> > What is the idea of this "clear" (X) button on Withdraw modal?
> 
> It's the validation status of the input. If the asset name you entered is valid it's a valid symbol, if not it's a cross.

Agreed with @gibbsfromncis , please leverage ant.design components as much as possible. 
In the current state (pre-ANT), did we only visualize a status there, or also any text (e.g. asset id)?
Either case, if the user opens this dialog and sees it the first time without having input anything, the "X" should not show.

**Comment by kapeer42** [comment]
@gibbsfromncis 
@sschiessl-bcp 
See new PR #2099

**Comment by gibbsfromncis** [comment]
@kapeer42 please do not close your issues by yourself.

**Comment by gibbsfromncis** [comment]
@kapeer42 why did you create new PR?

**Comment by kapeer42** [comment]
@gibbsfromncis to not `push --force` this one, the new one is a complete rewrite

**Pull request closed without merging**
