### PR TITLE
update node ver to 16+

### PR DESCRIPTION
**Pull request by xiangxn**
The upgrade content is as follows:
node 16.13.1
npm 8.2.0
Add yarn package management, it is very slow to install the lazy package by npm

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Can we please stick with npm for now? You can maintain the yarn.lock locally if you prefer it.

**Comment by xiangxn** [comment]
> Can we please stick with npm for now? You can maintain the yarn.lock locally if you prefer it.

Yes, of course you can use npm, this yarn is faster when you install the lazy package for the first time

**Comment by sschiessl-bcp** [comment]
I want us to agree on one source of truth when it comes to lock file. Your pull request introduces yarn.lock, we do already have package.lock.

I suggest we stick with package.lock, but you can use of course yarn locally (and then you need to take care that your local yarn.lock and package.lock are in sync)

**Comment by abitmore** [comment]
@sschiessl-bcp you are correct, using two package managers in the repository may lead to confusion, inconsistency and more maintenance work. However, I think introducing yarn as alternative package management is a good solution for the problem we are facing: it is hard for developers in China to access the sources listed in package.lock (npm). If @xiangxn only manages the file locally, it would prevent other developers in China to share the benefit, which is counterproductive. So my conclusions so far:
* add the yarn.lock file to the repository,
* document in README:
  * the package.lock file is the main one,
  * the yarn.lock file is for ease of development in China,
  * it is possible that yarn.lock is inconsistent with package.lock
* maintain consistency, best if it can be done via a bot (i.e. use Github Actions).
  * same packages and same versions in package.lock and yarn.lock
  * URLs in package.lock should be "official"
  * URLs in yarn.lock should be easy to access from China (use mirrors)

We can always delete the file later if it is too troublesome.

@sschiessl-bcp @xiangxn what do you think?

**Comment by sschiessl-bcp** [comment]
That's interesting. Why is yarn easier for China based developer than npm? The repository URLs should be the same?

**Comment by abitmore** [comment]
@sschiessl-bcp the URLs are different. In the yarn.yml file the packages are from mirrors.

**Comment by sschiessl-bcp** [comment]
Seems like taobao is also available for npm (e.g. https://developpaper.com/how-to-make-yarn-support-the-complete-acceleration-of-cnpm/). 

Considering there is a reason to improve connectivity for china based developers I'm fine with either approach, preferably one that uses the package.lock though. 

@xiangxn can you try if setting the mirror also works for npm via npmrc?

**Comment by xiangxn** [comment]
Using yarn is not just a problem of source, mainly because its operating mechanism is somewhat different from npm. For the same source, yarn is faster than npm. It is much better to retry and parallel installation when the network is disconnected. I will Use the same source as npm in yarn.lock.

**Comment by sschiessl-bcp** [comment]
Let me know when this is ready for review plz

**Pull request closed without merging**
