### PR TITLE
Issue 2325 - Gateway issues

### LINKED ISSUE #2325: [0.5] Legacy Deposit/Withdraw Citadel and WinEX issues
### As described in PR #2285 

WinEX has some issue making the app hang on loading as it doesn't catch failure. Citadel had some fetching issues as well, but did not hang the client. As they are the only ones not working, my plan was to do a new PR with a fix for them, but disable them until then to make sure we get the BlockTrades fix in an the application halting errors out for the time being.

_Originally posted by @startailcoon in https://github.com/bitshares/bitshares-ui/pull/2296#issuecomment-446231152_

- Fix currently disabled Citadel Gateway
- Fix currently disabled WinEX Gateway

### PR DESCRIPTION
**Pull request by startailcoon**
Closes #2325 

Citadel re-enabled as it works
WinEX removed as it's defunct and no longer maintained

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Have contacted Winex, they say their Gateway is still running. We shall see

**Comment by sschiessl-bcp** [comment]
Can you check this again and update the PR accordingly?

Winex said they only have withdrawal enabled atm, citadel should work.

**Comment by sschiessl-bcp** [comment]
Ping

**Comment by startailcoon** [comment]
Added to my to-do list.

**Comment by sschiessl-bcp** [comment]
If Winex wants back in, need to contact us. Off it goes.

**Pull request merged**
