### PR TITLE
Issue 2004 - Margin Modal updates (ANTify, Code split etc)

### LINKED ISSUE #2004: [7.5] Redesign & Antify Borrow Modal
Old design:

screenshot 2018-10-14 00 20 39

### PR DESCRIPTION
**Pull request by startailcoon**
Closes #2004, #2005, #2007 

This PR splits the logic from the view. 
View is in separate file named `{Logic}View.jsx`, here `BorrowModalView.jsx`.

## Fixes (among other)
- Default values for CR (2 * MCR), TCR (1 * MCR)
- Logic split of modal, clean and overhaul
- AmountSelector "Lock" icon
- NoTip on FormattedPrice enabled
- Layout
- Translation
- View/Modal file split
- Update remaining Debt
- Fixes to all refs to BorrowModal

See issue #2004 for screens and comments

### CODE REVIEW

**Comment by startailcoon** [comment]
I'll rebase and check this so it can be merged

**Comment by sschiessl-bcp** [comment]
1. Can you add a link to the new wizard? In the end we could simply do: "Read more & checkout the Explanation Wizard"

2. What is the initial value? 
image

3. I find the UI confusing. I would imagine that the currently locked one is green, and the unlocked once are blue (or even grayed out). Also there is no difference if I enter values in Debt or Collateral assuming that only Debt or Collateral value is entered. The one implies the other. Having said that, it is always like the: One is locked, the other two depend on each other. Summary and suggestion:
 - default: Ratio is locked (green icon), the other two are unlocked and grayed out, logic when typing in either Debt or Collateral as is
 - When the user selects the collateral field, or clicks on the green lock, the ratio gets a blue unlocked icon, the Collateral field gets a blue unlocked icon and the Debt a green locked icon. When user now types values in ratio, fields get updated as is now. Additionally, if user clicks on either of the lock icons of debt and collateral, the lock/unlock state gets switched, but the focus for user input remains on ratio and ratio remains unlocked. If user locks ratio, view is return to ratio green lock, other two grayed out.

**Comment by startailcoon** [comment]
1. Will do, are we talking about this URI `/borrow`?
2. It was due to the default collateral being set to 1 BTS. I've changed this to 0.
3. Will update based on your input. I agree with you on these parts and see only clarification with your suggestions. :+1:

**Comment by sschiessl-bcp** [comment]
Ping when done

**Comment by startailcoon** [comment]
Pong @sschiessl-bcp, it's done

**Comment by sschiessl-bcp** [comment]
image

Try to add more decimals to ratio

**Comment by startailcoon** [comment]
> image
> 
> Try to add more decimals to ratio

Will look at this tomorrow

**Pull request merged**
