### PR TITLE
Issue 2487 - Cloud account auth gateway action

### LINKED ISSUE #2487: [3] Portfolio Deposit/Witdhraw/Buy Icons doesn't render on logged out Cloud Accounts
When using a cloud account (non-binary account) the Dashboard Portfolio will not render the icons for Buy, Withdarw and Deposit modal actions. A cloud account has to be logged in to render these actions since the storage will return false for isMyAccount if it's logged out.

This will at times make cloud account users think that something is broken, as no warning or notification is visible let the user understand this requirement.

The requirements for isMyAccount is to make sure the user isn't performing a gateway/bridge action towards another users account, resulting in an address depositing to the wrong account. 

### Expected Performance
Icons for Buy, Withdraw and Deposit should render if the actions are possible (gateways and bridges are up) even for logged out cloud accounts. A tooltip warning should notify the user to login to perform the action.

### Extended Tasks
Refactor some of the code to perform better and reduce code

### PR DESCRIPTION
**Pull request by startailcoon**
<h2>General</h2>
Closes #2487 

If account is not in authorized accounts, or logged out cloud account, we never rendered Buy/Deposit/Withdraw icons, even if it was possible to be used after an authorization of the (cloud) account.

Cloud accounts where mostly affected of this, since it needed to be logged in to work. A timed out cloud account login would never render icons.

Combined functions for withdraw and deposit.

<h2>General</h2>
lease make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at 
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [x] Firefox
- [ ] Safari

_Please provide screenshots/licecap of your changes below_

bild

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
- BTS suddenly has a withdraw button
- Deposit retains state of previous token. Click on deposit e.g. "OPEN.BTC", then click to deposit any other asset

**Comment by startailcoon** [comment]
Deposit issue is know to me since before this PR. I will continue to look at that further.

I'll look at why BTS has a withdraw button.

**Comment by startailcoon** [comment]
Withdraw of BTS fixed. Mixed up a flag. Though, I can't get the modals to load through the lazy loading code used on Header.jsx applied by @sschiessl-bcp 

I suggest mergint this PR to apply the fixes for cloud accounts, while we try to fix the modal loading code in a new PR.

**Comment by startailcoon** [comment]
BTS withdraw fixed, due to a miexd up flag.
Deposit Modal update to reflext change in asset fixed.

**Comment by sschiessl-bcp** [comment]
Is this still using lazy loading now?

**Comment by startailcoon** [comment]
I've not touched the lazy loading that was changed in PR #2483 
It's still present at 

https://github.com/bitshares/bitshares-ui/blob/6512eabb622c504d84c9fde7626ed4cb98c1737e/app/components/Layout/Header.jsx#L1292-L1293

https://github.com/bitshares/bitshares-ui/blob/6512eabb622c504d84c9fde7626ed4cb98c1737e/app/components/Layout/Header.jsx#L1303-L1303

**Comment by sschiessl-bcp** [comment]
> I've not touched the lazy loading that was changed in PR #2483
> It's still present at
> 
> [bitshares-ui/app/components/Layout/Header.jsx](https://github.com/bitshares/bitshares-ui/blob/6512eabb622c504d84c9fde7626ed4cb98c1737e/app/components/Layout/Header.jsx#L1292-L1293)
> 
> Lines 1292 to 1293 in [6512eab](/bitshares/bitshares-ui/commit/6512eabb622c504d84c9fde7626ed4cb98c1737e)
> 
>  {this.state.hasDepositModalBeenShown && ( 
>      <DepositModal 
> [bitshares-ui/app/components/Layout/Header.jsx](https://github.com/bitshares/bitshares-ui/blob/6512eabb622c504d84c9fde7626ed4cb98c1737e/app/components/Layout/Header.jsx#L1303-L1303)
> 
> Line 1303 in [6512eab](/bitshares/bitshares-ui/commit/6512eabb622c504d84c9fde7626ed4cb98c1737e)
> 
>  {this.state.hasWithdrawalModalBeenShown && (

But the modal still works with that PR, correct?

**Comment by startailcoon** [comment]
That PR is merged to developer branch and this PR is based on that, so I would assume so yes. It works for me when testing.

**Comment by sschiessl-bcp** [comment]
I adjusted it now to show help cursor instead of pointer onhover. 

In general the flow in the UI is: action not available without login -> show login popup.

**Comment by startailcoon** [comment]
> In general the flow in the UI is: action not available without login -> show login popup. Accepted for now.

Fully agree. Will work on a fix for this soon. Desired here was to make sure cloud accounts aren't excluded from functionality due to the app missbehaving on not showing icons that should be viewed.

**Pull request merged**
