### PR TITLE
Iss 26 - Allow Modal Close with Keyboard Control

### PR DESCRIPTION
**Pull request by calvinfroedge**
This is just an implementation sample with a proposed approach for adding keyboard escape to modals.

A better implementation would be to have a single modal implementation which serves as a higher order component which modal implementation can implement. However, as that sort of pattern does not already exist, this is a possible compromise. Open to discussion either way.

Not ready to merge, just opening up discussion.

### CODE REVIEW

**Comment by calvinfroedge** [comment]
I decided to go ahead and add a higher order `BaseModal` component. This trims a bit of code from all other implementations as the close button is included in addition to providing the desired keyboard close behavior.

Should be easier to make future changes which affect all modals as well.

**Comment by wmbutler** [comment]
BitsharesUI Team

**Comment by svk31** [comment]
Tested and works well, nice work!

**Comment by calvinfroedge** [comment]
@svk31 Thanks!

**Pull request merged**
