### PR TITLE
update bitshares-ui

### PR DESCRIPTION
**Pull request by bxgzi**

### CODE REVIEW

**Comment by svk31** [comment]
What is XACOIN and why does it deserve to be included here?

**Comment by bxgzi** [comment]
XACOIN is an asset . What is the requirement for an asset to be included here?

https://wallet.bitshares.org/#/asset/XACOIN/

**Comment by svk31** [comment]
I see that it's an asset. What's the asset for though? Does it represent anything?

**Comment by bxgzi** [comment]
This asset can serve as a medium of exchange.

**Pull request closed without merging**
