### PR TITLE
1482 - Account page, Proposed transactions

### PR DESCRIPTION
**Pull request by kapeer42**
#1482
bts_1482_proposals

### CODE REVIEW

**Comment by kapeer42** [comment]
The approve appears when there is unsigned permissions available. The reject appears when there is at least one signed permission.

**Comment by wmbutler** [comment]
So, I guess that means it's possible for there to be an approve and a reject for the same transaction?

**Comment by abitmore** [comment]
@wmbutler by default you didn't have an opinion on a proposal, at that moment you can only approve;  after you've approved, you can change your mind, that's "reject".

**Comment by abitmore** [comment]
So if a transaction requires two approvals and one of them has approved, both approve and reject button will show.

**Comment by svk31** [comment]
This is really awesome, good job. I discovered one bug with key approvals which didn't get an option to be removed, and some proposal updating issues that were actually from the ChainStore not handling proposals properly. I've fixed the key removal in the merge commit and will make a new issue and commit for the ChainStore issues.

**Pull request merged**
