### PR TITLE
Merge OpenLedger login page

### PR DESCRIPTION
**Pull request by MikhailKavalenka**
**Issue:**
#2025

**Description:**
OpenLedger Login page on the separate /login route.

screen shot 2018-10-17 at 8 01 40 pm

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
- [ ] local wallet: when password is confirmed, the loaded local wallet file disappears before forwarded to dashboard
- [ ] after being logged in with local wallet and browsing to /login route, the existing local wallet is not loaded properly and login mode is switched to cloud login with the first account as the currentAccount
- [ ] after being logged in with local wallet and browsing to /login route, the existing local wallet is not presented as option to login
- [ ] after being logged in with cloud wallet, browsing to /login route is not possible
- [ ] pre-focus of accountname or password does not work (see review)
- [ ] cloud login password is at least 12 characters. In general this is confusing, expected password length is normally only shown on password creation, not login

**Comment by MikhailKavalenka** [comment]
@sschiessl-bcp ,
_local wallet: when password is confirmed, the loaded local wallet file disappears before forwarded to dashboard, does not look nice_
Fixed.

  _after being logged in with local wallet and browsing to /login route, the existing local wallet is not loaded properly and login mode is switched to cloud login with the first account of the local wallet as the currentAccount_
not sure I understand the issue, can you add some other details please?

  _after being logged in with local wallet and browsing to /login route, the existing local wallet is not presented as option to login_
We don't have such functionality that offers existing options for login.

  _after being logged in with cloud wallet, browsing to /login route is not possible_
Fixed.

  _pre-focus of accountname or password does not work (see review)_
Fixed.

  _cloud login password is at least 12 characters. In general this is confusing, expected password length is normally only shown on password creation, not login_
Removed placeholder with confusing min pass text.

BTW: I changes redirect after login/registration from account page (like it works in OL) to main page (like it works in BitShares). It allows to eliminate the code in componentDidUpdate of DecryptBackup.jsx that you found confusing. This code was intended to wait the account to be loaded in store and redirect to the account page.

**Comment by sschiessl-bcp** [comment]
> We don't have such functionality that offers existing options for login.

Current login popup functionality supports existing wallets (loaded from internal database, not .bin file) with preselection of last used wallet
image
image
Will merge without that to not hinder progress, but we need to maintain existing features.

After we are done with reworking the whole UX we need to aim for a single source of login code, I would envision that the login popup uses the mobile view of the login route
image

>> after being logged in with local wallet and browsing to /login route, the existing local wallet is not loaded properly and login mode is switched to cloud login with the first account of the local wallet as the currentAccount

> not sure I understand the issue, can you add some other details please?

Reproduce:
 - Login Mode Local Wallet. Create a local wallet (I have three accounts, not sure if it reproduces for one account)
 - Browse to `/login' route
 - Observe that Login Mode has been switched to Cloud Login, with one of the local wallet accounts as current account

**Comment by sschiessl-bcp** [comment]
> We don't have such functionality that offers existing options for login.

Current login popup functionality supports existing wallets (loaded from internal database, not .bin file) with preselection of last used wallet
image
image
Will merge without that to not hinder progress, but we need to maintain existing features.

After we are done with reworking the whole UX we need to aim for a single source of login code, I would envision that the login popup uses the mobile view of the login route
image

>> after being logged in with local wallet and browsing to /login route, the existing local wallet is not loaded properly and login mode is switched to cloud login with the first account of the local wallet as the currentAccount

> not sure I understand the issue, can you add some other details please?

Reproduce:
 - Login Mode Local Wallet. Create a local wallet (I have three accounts, not sure if it reproduces for one account)
 - Browse to `/login' route
 - Observe that Login Mode has been switched to Cloud Login, with one of the local wallet accounts as current account

**Comment by sschiessl-bcp** [comment]
> We don't have such functionality that offers existing options for login.

Current login popup functionality supports existing wallets (loaded from internal database, not .bin file) with preselection of last used wallet
image
image
Will merge without that to not hinder progress, but we need to maintain existing features.

After we are done with reworking the whole UX we need to aim for a single source of login code, I would envision that the login popup uses the mobile view of the login route
image

>> after being logged in with local wallet and browsing to /login route, the existing local wallet is not loaded properly and login mode is switched to cloud login with the first account of the local wallet as the currentAccount

> not sure I understand the issue, can you add some other details please?

Reproduce:
 - Login Mode Local Wallet. Create a local wallet (I have three accounts, not sure if it reproduces for one account)
 - Browse to `/login' route
 - Observe that Login Mode has been switched to Cloud Login, with one of the local wallet accounts as current account

**Comment by sschiessl-bcp** [comment]
Following error might be due to the above local wallet bug

- when switching from an existing local wallet to a new one
image
- when logging in with local wallet on a clean web wallet
image

Wiill hold off further testing until this is resolved.

**Comment by sschiessl-bcp** [comment]
Following error might be due to the above local wallet bug

- when switching from an existing local wallet to a new one
image
- when logging in with local wallet on a clean web wallet
image

Wiill hold off further testing until this is resolved.

**Comment by sschiessl-bcp** [comment]
Following error might be due to the above local wallet bug

- when switching from an existing local wallet to a new one
image
- when logging in with local wallet on a clean web wallet
image

Wiill hold off further testing until this is resolved.

**Comment by MikhailKavalenka** [comment]
> Following error might be due to the above local wallet bug
> 
> * when switching from an existing local wallet to a new one
>   image

This issue is related to LoginSelector and the way it deals with isIncognito. I made a little check to prevent the issue, although don't think the issue is in our code.

> * when logging in with local wallet on a clean web wallet
>   image
> 
> Wiill hold off further testing until this is resolved.

We tried to investigate the second error. It seems that the reason is in open/close consequence of iDB. Have not found the solution yet, we can make the investigation deeper and find the reason, but it will take time. Anyway it seems like the issue is not in our code, but OL code just illuminates the system fragility (the issue is reproducible in the BitShares codebase if you try lo switch the local wallet).

**Comment by sschiessl-bcp** [comment]
> the issue is reproducible in the BitShares codebase if you try lo switch the local wallet

Can you please give me steps to reproduce it?

**Comment by MikhailKavalenka** [comment]
> 
> Can you please give me steps to reproduce it?
> 
Here are the steps:
1. Login with local wallet.
2. Log out (lock account).
3. Open the login modal and try to login with another local wallet. There are errors in console: 

image

**Pull request merged**
