### PR TITLE
#1945  [Foundation Elimination] Block List

### PR DESCRIPTION
**Pull request by gibbsfromncis**
**Done**:
- Remove `block-list` from InitError and antify window
- Delete `AccountLeftPanel` as unused component
- Remove `block-list` from Chart Options modal and antify it
- Remove `block-list` from Market Picker modal and anitify it
- Remove `block-list` from QuoteSelectionModal and antify it

**Screenshots**:
### Init Error
screenshot 2018-10-10 04 20 14
screenshot 2018-10-10 04 19 26
screenshot 2018-10-10 04 18 30

### Chart Options
screenshot 2018-10-10 05 01 13

### Market Picker

screenshot 2018-10-10 05 29 25
screenshot 2018-10-10 05 29 18

Issue: #1945

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Was this branched off the new exchange layout, or the old?

**Comment by sschiessl-bcp** [comment]
New Exchange Layout is merged in (at least the big breaking changes). Please rebase

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp fixed

**Comment by sschiessl-bcp** [comment]
This is solved in another PR and will be forwarded then.

**Pull request merged**
