### PR TITLE
New multi level left sidemenu, fixes complex navigation and mobile ux

### PR DESCRIPTION
**Pull request by handijk**
I just checked out the latest changes and noticed the header is not mobile friendly anymore, i created a collapsible sidemenu for the header links and removed those links in the user dropdown on mobile.
Feel free to merge if it is considered useful.

### CODE REVIEW

**Comment by handijk** [comment]
I am creating a version of the solution described over here, #816 .
I think it will work out great, will be pushing somewhere over the weekend.

**Comment by svk31** [comment]
That issue is still under discussion so please be aware that these changes may never be implemented.

I personally think the new design is much better for mobile than the old one, since it works just as well on desktop and mobile. Not sure why another different menu on the left side changes that.

**Comment by handijk** [comment]
When i downloaded bitshares-ui for the first time a month ago, the navigation was hard to grasp, so i decided to make it more user friendly. After that there was one update that moved some items to the top bar and a huge list under the user menu, which made the navigation for a first-time user even more hard to understand. On mobile the header floated above the first rows of the main content, at least on small screen devices it did.

I am aware that this may not be implemented, but i really wanted to build a better navigation for this cool application because i know it will make it easier for first time users.

**Comment by svk31** [comment]
Don't get me wrong, I appreciate the effort. I just don't want to see you spend lots of time implementing something that may not be implemented. We probably need more discussion in the issue referenced in order to converge on a consensus solution for how to proceed.

**Comment by handijk** [comment]
No problem, i liked doing it in my spare time over the weekend. It would be great if you could check it out and let me know what you think.

**Comment by handijk** [comment]
image

image

image

image

image

**Comment by diogo-gomes** [comment]
I already suggested a side menu but in the right in this [issue](https://github.com/bitshares/bitshares-ui/issues/630#issuecomment-346954596). Can you merge your menu with the dropdown menu?

**Only one menu it's better UX.**

**Comment by handijk** [comment]
There are two things to consider reading your comments:

- Users have to think a lot harder about navigating around an application when the main navigation consists of more then approximately 4 items, having the menu in a single list will be confusing for first time users. By separating the account links/logout/help/settings and splitting up the main navigation in a graspable amount of main sections it is more clear what is where to be found for first time users.

- I am used to having a menu on the top/left and an account menu on the top right, it's like how most big sites seem to do it and i assume most average users are used to it. I also put links there that have not really a place in the main navigation because they are not really part of the application itself or just actions (and also seem to be put there a lot in other applications).

- Putting the account menu in the top right does not take up any horizontal or vertical space, the top bar is already there and there is enough room for some title to still be displayed, even on mobile when you do not display the full name and amount but only the account image there will be room in the header.

- The left sidemenu does take up some space in desktop view, but not very much because it will only show the menu icons and collapses over the content when hovered over.

A right sidemenu will work on mobile (and your mockup looks great) though i think it will be awkward on desktop and will also rule out a separate account menu (unless you put it at the left, which would be weird).

I do not think my pull request is a final solution for all navigation forever, but it is better to not make large changes at once and make small improvements at a time to actually see it work first in production and then get inspired with more improvements while working with the application itself because it is very difficult to nail this perfectly for every kind of user.

**Comment by diogo-gomes** [comment]
> having the menu in a single list will be confusing

With a menu with full height, we can create main options with one font size and subitems with another font size. We can also add a separator (thin line) to improve the user experience.

#  
> menu on the top/left and an account menu on the top right

If the account and the menu are different things, I don't dislike so much.
I also think that currently drop-down menu with all options together is really confusing.

#  
I agree with 3º and 4º topics

#  
> it will be awkward on desktop

Only if will be always visible with icons and I agree in this. If the side menu only be visible when it's open, I prefer the menu icon in the right but it's only an opinion.

#  
Whatever the decision on the positioning, etc, I propose that it be a side-menu like yours instead of a drop-down.
We get more space, the UI stays more modern, clean and better for the users.

**Comment by wmbutler** [comment]
We just made a big change. Let's hold off on this. I think it's a bad idea to do this hastily. I do agree that what we have in place is not optimal, however, as it relates to troubleshooting, it is quite easy to tell the user where to find things because everything is in the right menu (unless it's in the header).

I would encourage you to devise a means of placing everything in the right menu in some meaningful way to make our support roles easier.

**Comment by wmbutler** [comment]
https://tympanus.net/Development/MultiLevelPushMenu/index3.html#

See demo 3 which includes overlapping menus and back links.

This framework (but handled from the right side) might work well with hierarchies defined:

- Dashboard
  - Portfolio
  - Open Orders
  - Margin Positions
  - Activity
- Send
- Deposit
- Withdraw
- Settings
- News
- Help
- Exchange
- Explore
  - Blockchain
  - Assets
  - Accounts
  - Witnesses
  - Committee
  - Markets
  - Fees
- Advanced
  - Voting
    - Witnesses
    - Committee
    - Workers
  - Assets
  - Signed Messages
    - Sign Message
    - Verify Message
  - Vesting Balances
  - Whitelist
    - Whitelist
    - Blacklist
    - Whitelisted By
    - Blacklisted By
  - Permissions
    - Active Permissions
    - Owner Permissions
    - Memo Key
    - Cloud Wallet
- Accounts
  - Accounts
  - Contacts
  - Recent Activity
- account 1
- account 2
- account 3 etc..

**Comment by handijk** [comment]
Yes, i like the way that menu works, maybe i can work something out using your list.
Only advanced would be a second level menu, because the rest of the pages is navigated by tabs, am i correct?

**Comment by wmbutler** [comment]
@handijk might make sense to have the tabs mirror everything.

**Comment by Xeldal** [comment]
>A problem with using the left menu is that this involves replacing the bts logo with a burger. I think this branding is valuable and we should try to avoid removing it. 

@wmbutler I agree the bitshares logo should stay.  

A permanent left menu would eliminate the need for the burger and you could collapse it left to small icons like pictured above to regain the space if needed or even collapse fully to a thin line that pulls out like a drawer.

**Comment by wmbutler** [comment]
But I don't think that the burger should be to the left of the logo. This really only leaves the right side for the burger.

**Comment by Xeldal** [comment]
??
I'm saying there is no need for the burger. If the menu is static/permanent.

**Comment by diogo-gomes** [comment]
> A permanent left menu would eliminate the need for the burger...

In general UI and "standard", the logo is a link to home page and not the menu. Replace the burger menu with the logo will confuse a lot of users.

I agree with @wmbutler:
>But I don't think that the burger should be to the left of the logo. This really only leaves the right side for the burger.

**Comment by Xeldal** [comment]
>In general UI and "standard", the logo is a link to home page and not the menu. Replace the burger menu with the logo will confuse a lot of users.

You're quoting me as though I am suggesting using the logo as a menu.  I'm am not.  Read again.

**Comment by diogo-gomes** [comment]
Sorry @Xeldal, I though that ***A permanent left menu*** was out of question after the last changes to remove it.

But if you want my opinion regarding the permanent left menu again in the UI, it's:

In general UI and "standard", the logo is a link to home page and not the menu. **Delete the burger menu and put the logo in the same position** (above the permanent left menu) **will confuse a lot of users**.

@wmbutler, do you want a prototype/mockup for this?

**Comment by wmbutler** [comment]
@Xeldal your vertical line is not a well understood UX pattern. I wouldn't support it.

**Comment by handijk** [comment]
> I think you should put every endpoint in this menu whether they are handled by tabs currently or not. Then designers can freely remove tabs as the screen gets smaller without fear of losing accessibility.

That sounds like a good idea. I will try this out in my branch, i got a 2 level menu working locally inspired by the link you provided without too much hassle, so more levels shouldn't be much of a deal.

@diogogomes @Xeldal 

If you look at my screenshots at the top you can see i created a static left menu for desktop showing only icons and on hover it collapses and shows the full menu. That way there is no need for a burger menu icon on top, we still keep most of the horizontal space and the logo could link to the homepage.

For mobile i did use a hamburger icon for the menu instead of the logo because the icons on the left would take too much from the horizontal space. I understand @wmbutler needs the logo to be visible at all times on the top left and that seems reasonable to me, so for mobile we could put the burger menu on the right like he suggested.

I will push a new version of my branch somewhere over the weekend.

**Comment by Xeldal** [comment]
@handijk Sounds reasonable.  For mobile, what do you think of a menu that pulls out from the left with a drag_right?  It might be too hidden and not obvious for users I guess, but just an idea instead of needing a burger.

Also I noticed on older versions of amazon kindle (mobile/tablet) they use a very abbreviated hamburger to the left of their icon.  It's very small and doesn't take focus away from the main icon.  I don't have a pic at the moment but it's essentially just a vertical ellipsis "..." in the corner.  very slim.

Another idea, to avoid having to expand the menu from just icons.  consider something like what exodus does, where the menu item text is placed underneath the icon.  This would take a little more horizontal space than just the icons but much less than the side by side [Icon][Text].  You wouldn't need a burger and you also wouldn't need to collapse.

**Comment by wmbutler** [comment]
This back and forth over left side vs right side is really unproductive. My argument for putting everything on the right side is twofold:

- When troubleshooting, we can always say it's in the menu, not the right menu, not the left menu, just the menu.
- I think from a branding perspective it's important to have the logo always visible in the upper left corner.
- The menu on the right tends to cover over needed elements when it's expanded.

Can we try a cascading menu on the right as suggested before?

**Comment by sschiessl-bcp** [comment]
Will this be pursued further @handijk?

**Comment by wmbutler** [comment]
This should likely be closed since ANT will provide for responsive design.

**Pull request closed without merging**
