### PR TITLE
Issue 2205 + 2352 - Account Selector + Send Modal Style Guide

### LINKED ISSUE #2205: [3.5] Send Modal tweaks
**Is your feature request related to a problem? Please describe.**
Default keyboard action and focus states for buttons and fields in send modal

**Describe the solution you'd like**
- Enter key should trigger send and acknowledgements where appropriate
- Fields should be focused when modals open where appropriate

**Describe alternatives you've considered**
- [ ] Focus the `To` field when send modal opens
focus

- [ ] Enter key should trigger SEND button.
enter

- [ ] When login modal appears, "Password" field should get focus by default. If it's the cloud wallet, the username should have focus (but I haven't tested it since I don't have a cloud wallet).
- [ ] Login button should be activated by the Enter key.
focus

### LINKED ISSUE #2352: [6] Update AccountSelector with Style Guide components
Required for issue #2205 

- [x] Update `<AccountSelector>` with Style guide components.

## Sub-Tasks
- [x] #1984

### PR DESCRIPTION
**Pull request by startailcoon**
<h2>General</h2>
Closes #2205 - Send Modal Update<br />
Closes #2352 - Account Selector Update<br /><br />

Incluces both an update to the Account Selector to use the new Style Guide. It's been tested on sections that doesn't require the search (i.e. voting) as well as those that does use it (i.e. legacy send). Verified to work.

A few changes have been made to the design of the Send Modal at this update.

- Scam accounts can't be added to contacts directly when sending.
- Scam accounts will show a warning symbol on label (red) as well as in the list.
- Accounts that the user hold keys no longer display "remove contact". Instead it shows that the user has keys to mentioned account.
- Account in contact list now shows a filled star
- Account not in contact list shows an unfilled star
- Memo on proposed send will highlight in yellow 

Dropdown list shows accounts in the following order
1. Personal accounts
2. Contacts
3. Other matches to the search

<h2>General</h2>
lease make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at 
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [x] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [x] Light
- [x] Midnight

_Please provide screenshots/licecap of your changes below_

SendModalAntified_Asset
SendModalAntified_Voting
SendModalAntified_Propose
SendModalAntified

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Is there a reason for this massive margin?
image

**Comment by sschiessl-bcp** [comment]
Barter uses this icon
image
to show the memo message field. Should we do that here too? Is with or without memo the common use-case?

**Comment by sschiessl-bcp** [comment]
When opening the Send modal for the first time it shows the key exist message, now it only shows 
image

I think I found now the isse. First opening shows this:
image

If I click in the from field and type "1" it recognizes the new account, but doesnt change the value in the from field. I think the listeners are not firing correctly (note the change of id)
image

Expectancy: Either do not allow editing at all (and fire not listeners), or allow proper editing

**Comment by startailcoon** [comment]
> Is there a reason for this massive margin?

No. It's an old setting. I've reduced the margin from 1.5rem to 0.5rem.

> to show the memo message field. Should we do that here too? Is with or without memo the common use-case?

Difficult to say as we don't know what users use and how much they do. I'd imagine that memo isn't widely used though. We could replace it with an icon for reducing the space usage and make the application more unified. 

Where should we then add this icon? I can see two direct possibilities.
1. Keep the title Memo/Message and add an icon that the user can click to view the field.
2. Next to the "To" field on the right (no space on the left)

> When opening the Send modal for the first time it shows the key exist message, now it only shows

This is a cloud account issue and needs to be adressed sepperatly.

**Comment by sschiessl-bcp** [comment]
Was [this addressed](https://github.com/bitshares/bitshares-ui/pull/2517#issuecomment-471529838) as well?

**Pull request merged**
