### PR TITLE
Issue 2337 - Fix various testnet issues

### LINKED ISSUE #2337: [1] Fix TESTNET problem with no default preferred asset
Whenever a testnet does not use a default asset from the branding.js settings file (due to an unknown chain etc) the application would fail on a few of the components that had no failsafe.

This issue is to track hours for fixing those errors.

### PR DESCRIPTION
**Pull request by startailcoon**
Closes #2337 

Whenever default selected asset does not exists the application would crash on various components, like value calculations etc. that expected these to be available for query.

Default unknown chain token should be TEST

### CODE REVIEW

**Comment by ryanRfox** [comment]
Success! Thank you for this update. I was able to build it for my HTLC TESTNET and it resolved my WSOD when accessing the accounts page.

**Comment by sschiessl-bcp** [comment]
Or maybe @startailcoon can double-check?

**Comment by startailcoon** [comment]
I'll review this again

**Comment by sschiessl-bcp** [comment]
> I'll review this again

Did that happen?

**Comment by startailcoon** [comment]
No, but it will. I see no high priority on this PR as Ryan solved his issues based on my change. Though, it would be beneficial to work out the kinks in it, and it will be looked on when I have the time to.

**Comment by sschiessl-bcp** [comment]
inlcuded in https://github.com/bitshares/bitshares-ui/commit/74a0b427d0d7b20dcfd887cead8d7c8c948dc1b0

**Pull request closed without merging**
