### PR TITLE
iss 496 - ensure tables retain correct height

### LINKED ISSUE #496: [2] Extend black background to bottom of browser
@calvinfroedge I was hoping you could help with this. It's in branch 378-tables-rewrite. I'd like the black background to be pinned to the bottom of the browser, even if the table contents do not extend that far.

bgblack

### PR DESCRIPTION
**Pull request by calvinfroedge**
bg-extends

This change ensures that tables will always have the correct height, being at least fully extended to the bottom of the container.

To use, add `app-tables` to the `grid-content` container, and import `tableHeightHelper` into the component. There is a JS update that needs to get applied in both an interval and on tab change.

Resolves #496

### CODE REVIEW

**Comment by svk31** [comment]
I realize you put a lot of effort into this, but I'm not to happy about the flashing content that happens in the milliseconds before the background gets applied. 

Personally I would rather have a non-flashing screen without the black background extended all the way, it never bothered me in the first place. @wmbutler would you mind testing this locally and tell us how you feel about it before I merge it?

**Comment by calvinfroedge** [comment]
Might be able to prevent the flash by reducing the timeout interval

**Comment by wmbutler** [comment]
@svk31 I'll test it later today. In then meantime @calvinfroedge if you could add whatever you think may improve that behavior...

**Comment by svk31** [comment]
I still find it a bit jarring but I'll merge it and we can see if anyone else notices it.

**Pull request merged**
