### PR TITLE
Add scam accounts

### PR DESCRIPTION
**Pull request by abitmore**

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Done?

**Comment by abitmore** [comment]
Not yet :(

**Comment by sschiessl-bcp** [comment]
I guess there will always be more. Could you finish this and open new one for next round?

**Comment by abitmore** [comment]
Yes I can. What's the ETA for a new release?

**Comment by sschiessl-bcp** [comment]
> Yes I can. What's the ETA for a new release?

Trying to get a staging release out asap

**Comment by abitmore** [comment]
@sschiessl-bcp it's done this time. Please review.

**Comment by sschiessl-bcp** [comment]
How did you evaluate all those as scam accounts?

**Comment by abitmore** [comment]
Follow the account histories.

**Comment by shulthz** [comment]
If we can make a colour-coded for these offical CEX address in UI？

**Pull request merged**
