### PR TITLE
#1870 Fix clipboard issue

### PR DESCRIPTION
**Pull request by gibbsfromncis**
Fix of issue #1870

@sschiessl-bcp please before do merge:
1) Make fork of `react-copy-to-clipboard` repo
2) Replace link on `package.json` file to our fork 

We need this to prevent any future invasion by outside packages we use in our app development

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Waiting for re-evaluation of the respective issue

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp estimate was updated. Added new feature.

**Comment by startailcoon** [comment]
Please ensure this is fixed before merging https://github.com/bitshares/bitshares-ui/issues/1870#issuecomment-425972696

**Comment by sschiessl-bcp** [comment]
Old behavior is maintained for now. Consistent refactoring was done.

**Pull request merged**
