### PR TITLE
New openledger api

### LINKED ISSUE #2572: Adaptation to the new openledger api
Openledger backend team implemented new api, which include these methods:
/exchanges (returns the list of supported exchange options, i.e what asset can we exchange to what. It contains information about gateway fee for each exchange option in the list.)
/exchanges/{exchange_id}/transfer/source/prototype?destination_address=<string>&destination_memo=<string> (returns to a user a "prototype" of a transfer that the user has to make in order to exchange his assets (that he sent) to another assets using given exchange option.)
/exchanges/{exchange_id}/transfer/destination (Method allows to check the validity of the transaction in the blockchain. This method must be called by browser/client when user wants to exchange one asset to another, and serves to check whether wanted operation in destination blockchain can be performed or not)

Need adaptation to this new api. But /exchanges returns incomplete list of exchanges, therefore some coins must work with old api.

### PR DESCRIPTION
**Pull request by OpenLedgerApp**
<h2>Adaptation to the new openledger api</h2>
Closes #2572

<h2>General</h2>
Openledger backend team has implemented a new api, which includes these methods:

1. /exchanges (returns the list of supported exchange options, i.e what asset can we exchange to what. It contains information about gateway fee for each exchange option in the list.)
2. /exchanges/{exchange_id}/transfer/source/prototype?destination_address=&destination_memo= (returns to a user a "prototype" of a transfer that the user has to make in order to exchange his assets (that he sent) to another assets using given exchange option.)
3. /exchanges/{exchange_id}/transfer/destination (Method allows to check the validity of the transaction in the blockchain. This method must be called by browser/client when user wants to exchange one asset to another, and serves to check whether wanted operation in destination blockchain can be performed or not)

Need adaptation to this new api. But /exchanges returns incomplete list of exchanges, therefore some coins must work with old api.

### CODE REVIEW

**Comment by dot5enko** [comment]
> Need adaptation to this new api. But /exchanges returns incomplete list of exchanges, therefore some coins must work with old api.

@OpenLedgerApp Is there an intension to support them in the future?

**Comment by OpenLedgerApp** [comment]
@dot5enko we are gradually moving to a new api, and when all coins will work with new api, we will need to refactor because now gateway system works for both api.

**Comment by sschiessl-bcp** [comment]
Due to lack of funding dot5 is not continueing with this work. We will need to re-evaluate and push gateway integrations now.

I will catch up on this matter and coordinate.

**Comment by sschiessl-bcp** [comment]
Is this PR up-to-date?

**Comment by sschiessl-bcp** [comment]
Please let me know what's happening. Does the current integration still work flawlessly?

Your gateway will be deactivated with the next release, it can be dynamically activated again.

**Comment by sschiessl-bcp** [comment]
> Please let me know what's happening. Does the current integration still work flawlessly?
> 
> Your gateway will be deactivated with the next release if not working, it can be dynamically activated again once integration is fixed.

Closing this for now, please come back to me when you are ready. Gateway deactivated in the meantime.

**Pull request closed without merging**
