### PR TITLE
#2605 [Translation]"Force Settlement price" in the Publish feed should be "Feed price"?

### LINKED ISSUE #2605: [alexandr-masl][0.25][Translation]"Force Settlement price" in the Publish feed should be "Feed price"?
图片

"Force Settlement price" in the Publish feed should be ""Feed price"?
https://github.com/bitshares/bitshares-ui/blob/c5edb498b6e2db7abdfb1f7974a02222378cd58e/app/assets/locales/locale-en.json#L763

### PR DESCRIPTION
**Pull request by alexandr-masl**
<h2>General</h2>
Closes #2605

[Insert description of what you did, any description how to test or check your changes are welcome]

<h2>General</h2>
lease make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at 
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [ ] Check for unused code
- [ ] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [ ] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [ ] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Please fill out the PR template

**Comment by sschiessl-bcp** [comment]
Is the value that is shown actually the feed price?

Changing the translation like that is not acceptable since it causes confusion. `settlement_price` must translate to settlement price.

**Comment by alexandr-masl** [comment]
will check now one more time

**Comment by alexandr-masl** [comment]
photo_2019-04-16_16-29-04

**Comment by alexandr-masl** [comment]
> Is the value that is shown actually the feed price?
> 
> Changing the translation like that is not acceptable since it causes confusion. `settlement_price` must translate to settlement price.

yes it is, did you mean - i have to fix key settlement_price to feed_price too ?

**Comment by sschiessl-bcp** [comment]
Closed manually, this PR is considered accepted.

**Pull request closed without merging**
