### PR TITLE
Add "Maximize Collateral" button to Borrow Modal.

### LINKED ISSUE #901: [.5] Add Max Collateral Feature To Margin Adjustment Window
Imagine having a "Use Maximum Collateral" option right below the collateral ratio slider which would use as collateral all available BTS currently in the active account. I am always doing this manually. If I am going to sleep I always want to have the maximum collateral just in case some drastic crash happens.

This would help reduce margin calls because it would lower the margin call price for users who don't know they can enter more collateral than the 5% precision slider allows.

The only issue I see with this is having some BTS left over for fees. Maybe the maximum could actually be slightly less than the maximum, leaving only enough BTS to match the current price for collateral adjustment so that the user can unlock their BTS at a later date. We can't have the user stuck with locked up collateral and no fees to unlock it.

### PR DESCRIPTION
**Pull request by pnomolos**
"Maximize Collateral" will need to be translated.  I didn't add it to the translation matrix because I'm not entirely sure how that's set up and didn't want to inadvertently cause breakage for someone in a different locale.

- Fixes #901

### CODE REVIEW

**Comment by svk31** [comment]
The positioning of the button is a bit weird.

image

Also, you need to take into account any existing collateral. In the above case, clicking the button sets collateral to 136k, which means there's still 53k BTS left to use since that was the value of the original collateral. The two need to be added.

**Comment by pnomolos** [comment]
@svk31 Should I just put the maximize collateral button to the right of "Reset"?  And I'll fix the other item :)

**Comment by svk31** [comment]
Yea on the right side I guess is fine, just not grouped with the two other buttons.

**Comment by pnomolos** [comment]
@svk31 Changes made.  I also added some logic to ensure the collateral ratio doesn't go above 1000 when the button is clicked :+1:

**Pull request merged**
