### PR TITLE
2837-KeyImportFromWIF

### LINKED ISSUE #2837: [mrugakshee][1.25] Unable to Import Key from WIF
**Describe the bug**
Unable to import private key (WIF) to `BITSHARES 3.1.190618`

**To Reproduce**
1. Login with: key file (local wallet)
2. Navigate: Settings >> Restore/Import
3. Select: Import a private key
4. Paste: privKey (WIF)
5. Click: Submit 

Result: no UI response. Same if the field is left blank and click submit.

**Expected behavior**
In the past, the privKey is added to the wallet and the associated account(s) is displayed. Also, if the field is blank, or not a WIF format (length?) the UI should inform the user of the error.

### PR DESCRIPTION
**Pull request by mrugakshee**
<h2>General</h2>
Closes #2837 

- Fix UI breakage in WIF key field
- Add error messages for incorrect WIF
- Add translations for error messages
- Display associated account(s) for WIF

Screen Shot 2019-07-22 at 1 43 44 PM
Screen Shot 2019-07-22 at 1 43 35 PM
Screen Shot 2019-07-22 at 1 43 16 PM

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
I'm using my local wallet that already has a couple accounts in it. Now the importing hangs in loading
image

Error message is this, not sure if related?
image

**Comment by mrugakshee** [comment]
@sschiessl-bcp The bug with the loading screen persisted when I fixed the UI breakage that leads to the screen you have pictured, however, I didn't take a look at the loading screen since it wasn't mentioned in Expected Behaviour or Goals of the listed issue! Did I misread the goals?

**Comment by sschiessl-bcp** [comment]
I can't import a private key, so it's in scope.

In general: I would rather have you expand the scope / estimate and actually make the screen work while you are working on it anyways

**Comment by sschiessl-bcp** [comment]
@mrugakshee will you fix it please?

**Comment by atlantic-blockchain** [comment]
> I can't import a private key, so it's in scope.
> 
> In general: I would rather have you expand the scope / estimate and actually make the screen work while you are working on it anyways

Okay sure, that makes sense, sounds good! 
End goal = getting past the persisting loading screen and being able to download WIF keys. Got it 👍

**Comment by mrugakshee** [comment]
> I can't import a private key, so it's in scope.
> 
> In general: I would rather have you expand the scope / estimate and actually make the screen work while you are working on it anyways

Okay sure, that makes sense, sounds good!
End goal = getting past the persisting loading screen and being able to download WIF keys. Got it 👍

**Comment by mrugakshee** [comment]
@sschiessl-bcp Fixed! 

The worker was hanging and the line in webpack config fixed it. This article helped  - https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

Screen Shot 2019-08-13 at 12 34 49 PM

**Comment by sschiessl-bcp** [comment]
Neat!

**Comment by sschiessl-bcp** [comment]
Please state your efforts, and updated bounty request

**Comment by mrugakshee** [comment]
> Please state your efforts, and updated bounty request

**Total Hours**: 5 hours
**Quality Hours**: 3 hours

**Pull request merged**
