### PR TITLE
2592 TBAPI-0KA - Group by asset

### LINKED ISSUE #2592: [14][TBAPI-0KA] Open Orders Tab: Group By "Trading Pair"
I would like to propose some improvements in Open Orders Tab
I currently have many open orders on many diferent markets and I'm always looking to find answers for few questions:

- What is the sum of every base asset I want to sell or buy on each pair.
- What is the sum of every quote asset I want to sell or buy on each pair.
- What is the average order price on each pair.
- What is the current order value for each pair
- What is the expected value of the order for each pair.

Additionally I would like to be able to: 

- select all orders and cancel them with one click (this works now)
- select all orders on the same pair and cancel them with one click

I am attaching two mockups below.
I think that the accordion would be great for this purpose.

Open-Orders

Screenshot_1

### PR DESCRIPTION
**Pull request by TBAPI-0KA**
<h2>General</h2>
Closes #2592:

- significant refactoring of Open Orders table sub-components for Exchange and Account;
- replaced old Table with the Ant one;
- added reusable Collapsible Table component;
- added "Group by asset" selector;
- added grouped view with collapsible tables with summarized information in the header;
- mass select functionality;
- kept all previously working logic: order cancels, changing market direction, etc.

Testing: Open Orders tab on the Account page.

<h2>Code Preparation</h2>

- [x] Check for unused code
- [x] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

This PR contains a few files with reformatting changes only. I found this only on PR submitting stage. These changes were introduced in merge commit by prettifier. There's no simple way to ignore them on commit stage, except explicit flag passing, which is obviously not good for a merge commit. If required, I can override them by another commit. Otherwise, the following files could be safely ignored:
- app/components/Account/AccountPortfolioList.jsx
- app/components/Blockchain/OperationAnt.js
- app/components/Dashboard/MarketsTable.jsx
- app/components/Explorer/Assets.jsx
- app/components/Modal/SettleModal.jsx

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_The branch has been tested in all themes_

- [x] Dark
- [x] Light
- [x] Midnight

2019-05-13 08_04_30-BitShares 2 0 190410-rc2
2019-05-13 08_04_45-BitShares 2 0 190410-rc2

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Is the "Group by asset" column selection on purpose or something broken there? It seems weird to have one column per word
image

**Comment by TBAPI-0KA** [comment]
Do you mean words like "Sell", "for", etc? Well, I did everything exactly as on mockups. If you have any idea how to visualize it better - I agree that would be nice...
The more interesting question is why the last column doesn't show the amount in BTS. I haven't touched the calculation logic there, and I can see it. Maybe something with "preferred unit" setting, or so.

**Comment by sschiessl-bcp** [comment]
Can you try to have sentence "Buy XX YY for ZZ WW" not be so cut in terms of margin. It should feel as if the sentence as a whole is equivalent to the other columns
image
 - margins of columns that are representing the sentence should be "as big as needed to fit content"
 - whole sentence is left align

Please add the column titles where you have only numbers in the title (as comparable to mockup)

**Comment by TBAPI-0KA** [comment]
- kinda hacky, but "fit to content" mode is implemented. It looks as a sentence and as the separate columns at the same time - I think all types of users will be satisfied.
- however, visually column looks like it's centered, not left-aligned. In fact, it is left aligned - you can check that space is taken by "Order ID" column. The thing is that all the rest columns take space evenly. And something should fill empty spaces on large screens. The grouped table looks perfect on screens ~1400 px. If you look carefully at "not grouped mode", you'll see that empty space partially is taken by "Order ID" column, partially - by "Description", and "Price" with "Market price" are left-aligned, while "Value" is right-aligned, which also hides some empty space. With grouped columns, I've aligned the first two and a set of description columns to left, the last three - to the right. If you want to put most of the empty space between description and price columns, I'm not sure how to better handle this. The only approach I see is to set max-width for all the rest columns and add an empty column after the description. However, it looks like an ugly hack. Another compromise approach is to set max-width only for the first two columns - this will align the description visually to the left. However, this way all the empty space will be distributed between the last three columns. Please let me know what you think.
- a very good thing - this somehow fixed jumping of collapsed and uncollapsed table.
- titles have been added.

**Comment by sschiessl-bcp** [comment]
- image
The average price seems incorrect (see account fabian). Also, if the table is uncollapsed and I click in a row, the table collapses again. Should stay open.

 - 
image
If I click the row to invert price, the table are also re-positioned, see below
image
Expectancy: Sorting of tables remains

 - 
image
Tables should not have margin on the left and the right side (see portfolio)

**Comment by TBAPI-0KA** [comment]
- I've checked the average price calculation, it's correct. One time - in the code, second - on the calculator. Please put the following import on line 15 in \app\components\Account\AccountOrders.jsx:
```
import {groupBy, sumBy, meanBy, map} from "lodash-es";
```

and the following code on line 213:
```
let arr = map(groupedDataItems, dataItem =>
    dataItem.order.sellPrice().toReal(true)
    );
console.log("arr", arr);

let sum = sumBy(groupedDataItems, dataItem =>
    dataItem.order.sellPrice().toReal(true)
);
console.log("sum", sum);

let manAvg = sum / groupedDataItems.length;
console.log("manAvg", manAvg);

console.log("averagePrice", averagePrice);
```
and then check the console, if you have any doubts regarding correctness.
- I mentioned issues with the click on the issue, because they use previous logic, and it's quite not a part of this task. However, I've found a relatively quick way to fix this. Changes are committed.
- margins - removed. Please take into count that when I started this task, all tables on the Account page has those margins, and my personal opinion is that it's better to add margins everywhere instead of removing them on this single table.

Stefan, can you make sure that estimation on this task is agreed with @startailcoon? More details on the ticket description. I can make as many changes as requested, no problem, but it looks like this task grown too much in its scope from the initial idea.

**Comment by sschiessl-bcp** [comment]
Increasing the estimate for added features that were not in initial description is no problem. Also increase in estimate for onboarding new devs is also acceptible to some extend. And with that I mean we probably won't agree on 32 as you stated in the issue, but certainly more than 14 considering the research you've done and additional features. 

I ll get back to you on that after reviewing again

**Comment by sschiessl-bcp** [comment]
This PR is completed from your view, yes?

**Comment by sschiessl-bcp** [comment]
> * image
>   The average price seems incorrect (see account fabian). Also, if the table is uncollapsed and I click in a row, the table collapses again. Should stay open.

The average price is 0.7240 while every price of every positon is over 1. How is that possible?

**Comment by TBAPI-0KA** [comment]
I hardly understood where you took this screenshot (it's for inversed market direction), but it's fixed now.

**Comment by sschiessl-bcp** [comment]
> I hardly understood where you took this screenshot (it's for inversed market direction), but it's fixed now.

I was just clicking around with no aim and found that state :)

**Comment by TBAPI-0KA** [comment]
Huh, nice :) I've tested with all the diligence, but indeed miss this bug.

**Pull request merged**
