### PR TITLE
Disable RuDEX

### PR DESCRIPTION
**Pull request by abitmore**
<h2>General</h2>

Rudex is being migrated from Bitshares to Graphene:

https://steemit.com/rudex/@rudex/announcement-of-rudex-migration-from-bitshares-to-graphene-dates-and-terms

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [ ] Check for unused code
- [ ] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [ ] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [ ] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
We would have the option to immediately show the warning icon, and show the link to the Steem article in the Settings via on-chain config
image

**Comment by sschiessl-bcp** [comment]
If I remember correctly we can even put a [comment with it](https://github.com/bitshares/bitshares-ui/blob/76b8d95184f831db7c80ad0b0dd77fd9b790e8e9/app/lib/chain/onChainConfig.js#L73), would need to test this though.

The config part could be changed to something like

```
"gateways":
{
    "OPEN": { "enabled": false }, 
    "BRIDGE":{ "enabled": false },
    "RUDEX":{ "enabled": false, "comment": "Some message" } 
} 
```

**Comment by abitmore** [comment]
I remember the on-chain config feature was discussed, but I'm not sure if it's implemented already. If it's implemented then we don't need to update code every time.

**Comment by sschiessl-bcp** [comment]
> I remember the on-chain config feature was discussed, but I'm not sure if it's implemented already. If it's implemented then we don't need to update code every time.
> 
> Btw having comments is good too, I wonder where is the best place to show them.

Connect to the testnet with a UI, then reload (the asset configuration is only loaded in beginning and decides according to the initially connected node).

The config asset is https://develop.bitshares.org/#/asset/NOTIFICATIONS

The assets blacklist is
```
"blacklists":{ "assets":[ "PRD" ], "accounts":[] }
```
It shows in the UI like follows
image

Gateway comments are here
```
 "gateways":{ "OPEN":{ "enabled": false, "comment": "OpenLedger Gateway API Integration is defective." }, ...
```
The comment shows up at the end of first paragraph
image

So seems to be working alright

**Comment by sschiessl-bcp** [comment]
Suggestion

```
This asset is used for decentralized configuration of the BitShares UI placed under bitshares.org. { "notifications":[ { "type":"warning", "begin_date":"21.11.2020", "end_date":"31.12.2021", "content":"SCAM WARNING: BURN option is not a withdrawal. It is actual burn of an asset back to its owner." }, { "type":"critical", "begin_date":"21.11.2020", "end_date":"31.12.2021", "content":"WARNING: Users of the BitShares blockchain, DO NOT ACCEPT suspicious offers to trade tokens on private markets or tokens that are not listed in Withdrawals section of the Wallet UI or in default market pairs." } ], "blacklists":{ "assets":[ ], "accounts":[ ] }, "gateways":{ "OPEN":{ "enabled": false }, "BRIDGE":{ "enabled": false }, "RUDEX":{ "enabled": false, "comment": "RuDEX for Bitshares blockchain is disabled since 27.05.2021, see https://steemit.com/@rudex" } } }
```

Diff to current description
```
"RUDEX":{ "enabled": false, "comment": "RuDEX for Bitshares blockchain is disabled since 27.05.2021, see https://steemit.com/@rudex" }
```

**Comment by abitmore** [comment]
@sschiessl-bcp even we can disable a gateway on chain, still need a PR to update Featured Markets, right?

**Pull request merged**
