### PR TITLE
Feature: Message signing and verifying

### PR DESCRIPTION
**Pull request by sschiessl-bcp**
Dear BitShares community,

this feature pull request adds message signing and verifying into the advanced features section in the account overview. The user can write and sign messages and verify ones from other accounts, see attached screenshots.
screenshot_20171109_141856
screenshot_20171109_141919

The format of a message follows common styleguides for signed messages. It contains a header / meta /  signature / footer tag (this format is of course up to discussion):

-----BEGIN BITSHARES SIGNED MESSAGE-----
[message from the account]
-----BEGIN META-----
account=[account name]
memokey=[account memo public key]
block=[last irreversible block]
timestamp=[current time]
-----BEGIN SIGNATURE-----
[signature]
-----END BITSHARES SIGNED MESSAGE-----

I simply created the functionality without concerning myself too much with the visualization, I would like to ask you for interface design suggestions here as well. Also, please do not hesitate to give any feedback, comments or improvement suggestions. Furthermore, if I may ask for that, I would like feedback on my code style (potential no-gos), and maybe if there are standards that I overlooked to use that the BitShares platform is using.

Best regards,
 Stefan Schießl
 Blockchain Projects BV

### CODE REVIEW

**Comment by svk31** [comment]
This looks awesome, nice work! @wmbutler I suppose you'd like to offer some input on the UX?

**Comment by xeroc** [comment]
This feature offer some very nice possivilities ... No people can proof ownership of an account to anyone without sending transactions around ..

**Comment by svk31** [comment]
I'm merging this as is and we can work on the styling etc later, thanks for the PR!

**Comment by sschiessl-bcp** [comment]
Thank you @svk31 . I'm happy that it got accepted. I'll be happy for styling suggestions! 

One thing that is currently missing as functionality: The setting of the "Verify while typing" slider is not stored on an per-user basis, it is simply off everytime the user restarts the app. 
What is the best way to store that configuration per-user?

**Pull request merged**
