### PR TITLE
Removed dead coins

### PR DESCRIPTION
**Pull request by froooze**
Added: RUDEX.EOS, RUDEX.WLS, RUDEX.SMOKE pairs
Removed delisted coins from OL and Blockpay. https://dex.openledger.io/news/some-openledger-dex-gateways-disabled/

<h2>General</h2>
Closes #[Insert issue number]

[Insert description of what you did, any description how to test or check your changes are welcome]

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at 
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [ ] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by abitmore** [comment]
BLOCKPAY is dead? Link please?

**Comment by abitmore** [comment]
PPY is dead as well?

**Comment by froooze** [comment]
@abitmore:
https://blockpay.ch/
https://dex.openledger.io/news/some-openledger-dex-gateways-disabled/

**Comment by abitmore** [comment]
The BLOCKPAY token is still free to trade.

**Comment by sschiessl-bcp** [comment]
@ruslansalikhov please comment

**Comment by ruslansalikhov** [comment]
> @ruslansalikhov please comment

This PR contains these changes - https://github.com/bitshares/bitshares-ui/pull/2628 (@xanoxt)

**Comment by sschiessl-bcp** [comment]
> > @ruslansalikhov please comment
> 
> This PR contains these changes - #2628 (@xanoxt)

Thanks, will adjust accordingly

**Pull request closed without merging**
