### PR TITLE
change expiration logic for limit/scaled forms

### LINKED ISSUE #2356: [1] Datetime picker Expiration - Missing tooltip
**Describe the bug**
1. The Datetime picker expiration is missing the tooltip once the default (1year) is clicked.
181212rc-1_datetime_picker_1_capture

2. It is not clear for the user that they can specify the expiry date and time outside of the specific pull 
   down. 
3. Clicking on specific lastly contains specific twice.181212rc-1_datetime_picker_1_specific_capture
4. Clicking the second specific closes the pull down list.

  

**To Reproduce**
1. Go to Exchange tab
2. Click on the BTS tab for BitCNY:BTS pair
3. Scroll down past the chart to buy/sell
4. Click on default expiration of 1 year
181212rc-1_datetime_picker_1_1yr_capture

5. See error of missing timedate picker tooltip; see specific timedate picker tooltip
181212rc-1_datetime_picker_1_capture

6. Click on specific tooltip noting a second specific in the pull down list
7. Click on the second specific in the pull down list noting it closes the pull down list
8. Click the default timedate shown noting a calendar popup
181212rc-1_datetime_picker_1_2_capture
181212rc-1_datetime_picker_dec_capture

**Expected behavior**
1. Timedate picker tooltip if default (1year) is clicked
    for a better user experience and self help
2. Clicking specific or the current datetime picker (after clicking default 1 year) opens up the calendar (as in previous releases I think)
3. Consider removing the second _specific_ from the pull down list if possible to eliminate confusion. Or, replace the second word "specific" with "advanced"(same # letters) that opens up the calendar. The other options of 1 hour to 1 year are quick and easy.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera 
 - Version 56.0.3051.116
 - Release 181212rc-1

**Additional context**
Please see #2355

### PR DESCRIPTION
**Pull request by OpenLedgerApp**
<h2>General</h2>
Closes #2356  

Сhange expiration logic.
It took more time then planned, because:
-it was necessary to change logic for both forms(limit/scaled).
-Had some difficulties with implementation a datePicker into option of Select and re-change of "Specific" option.

<h2>General</h2>
lease make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at 
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [+] Check for unused code
- [+] No unrelated changes are included
- [+] None of the changed files are reformatting only
- [+] Code is self explanatory or documented
- [+] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [+] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [+] Dark
- [+] Light
- [+] Midnight

_Please provide screenshots/licecap of your changes below_

Added tooltips for options from 1 hour to 1 year

image

To open up the Calendar you should click on "Specific" option

image

After choosing a date dropdown will look like. And you can always click on the date in dropdown to change it in the Calendar.

image

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
See https://github.com/bitshares/bitshares-ui/issues/2356#issuecomment-487916601

**Comment by sschiessl-bcp** [comment]
The new UI looks smooth, thanks!

My comments:
 - default seems to be one hour expiration, was that change on purpose?
 - when opening the exchange I see errors related to those changes
    - `Warning: Failed prop type: Invalid prop `value` of type `boolean` supplied to `CalendarMixinWrapper`, expected `object`.`
   - `checkPropTypes.js:19 Warning: Failed prop type: Invalid prop `value` supplied to `Picker`.`

Can you please have a look?

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp, thanks! After looking comments I fixed two last items, but the item "is it possible without much effort to have the OK button of the date picker on the top of the picker?" will take more time.

**Comment by froooze** [comment]
The datapicker needs `Text_Padding` : 1`,  background should be darker with the same style as input fields.

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp, thanks! After looking comments I fixed two last items, but the item "is it possible without much effort to have the OK button of the date picker on the top of the picker?" will take more time.

Ok, let's not do that then now

**Comment by sschiessl-bcp** [comment]
> The datapicker needs `Text_Padding `, with the same style as _Select input_.
> https://styleguide.bitshares.org/

Now I merged it without seeing this .. can you elaborate (screens maybe?) what you mean plz?

**Pull request merged**
