### PR TITLE
Add API node api.bts.mobi

### PR DESCRIPTION
**Pull request by abitmore**
Maintained by me. Please help test.

### CODE REVIEW

**Comment by litepresence** [comment]
added here https://github.com/litepresence/extinction-event/blob/master/bitshares-nodes.py

fails to connect (not timeout) without /ws or /wss suffix added

with suffix, tested to northeast USA it is the fastest node in the world; 0.40 connection time: 

https://pastebin.com/f7fewQjT

**Comment by abitmore** [comment]
@litepresence thanks. I just changed config to serve all URI but not only `ws*`. Please check again.

**Comment by litepresence** [comment]
Responds to all 3 methods now:
```
('ping:', '0.41', 'wss://api.bts.mobi')
('ping:', '0.57', 'wss://api.bts.mobi/ws')
('ping:', '0.41', 'wss://api.bts.mobi/wss')
```

**Comment by litepresence** [comment]
not sure what is causing it... but on microDEX I print multiple concurrent processes which display orderbook as an animation between nodes; your node is rounding differently when displaying some of the market history; for example one of the BTS:OPEN.BTC recent transactions; @ unix 1522693533 is for    0.00002004 99953719 you are displaying 0.00002013 42281879 ; volume 0.0015 BTS

**Comment by abitmore** [comment]
@litepresence please also print exact time range next time.

**Comment by litepresence** [comment]
that trade mentioned was at  unix time 1522693533 as mentioned, not sure what you mean by time range

**Comment by abitmore** [comment]
> between nodes; your node is rounding differently

@litepresence who are the other nodes? Please list them so we can check if they're running correct version. AFAICT all nodes should upgrade to 2.0.180328 due to the security fixes (and those earlier than 180202 are buggy).

**Pull request merged**
