### PR TITLE
Update apiConfig.js

### PR DESCRIPTION
**Pull request by sschiessl-bcp**
- remove ES nodes
- add bitshares.org node

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
@apasia-tech please update with proper details

**Comment by abitmore** [comment]
Note the `us.` and `asia.` nodes aren't working. I heard they will provide ES nodes too.

**Comment by abitmore** [comment]
Note: need to update the magic number `[3]` in `AccountReferralsTable.jsx` when removing/adding ES nodes. Not sure if need to update anywhere else. https://github.com/bitshares/bitshares-ui/blob/219c0208051c1c93cb0bf834733f7cbd95dd1df3/app/components/Account/AccountReferralsTable.jsx#L54-L55

**Comment by sschiessl-bcp** [comment]
> Note: need to update the magic number `[3]` in `AccountReferralsTable.jsx` when removing/adding ES nodes. Not sure if need to update anywhere else.
> 
> https://github.com/bitshares/bitshares-ui/blob/219c0208051c1c93cb0bf834733f7cbd95dd1df3/app/components/Account/AccountReferralsTable.jsx#L54-L55

Will do

**Comment by sschiessl-bcp** [comment]
@dls-cipher please open a new PR with your fixed API nodes ... merging for now

**Pull request merged**
