### PR TITLE
#2813. send to missing translation

### LINKED ISSUE #2813: [0.5][3.1.190618-rc1] Send - missing translation
**Describe the bug**
When I go to send, there is a translation missing

**To Reproduce**
1. Go to send
2. click on To
3. See error

**Expected behavior**
No error

**Screenshots**
missing-translation

**Desktop (please complete the following information):**
 - OS: MX-Linux

**Additional context**
Error does solve, when used a second time sometimes by itself

### PR DESCRIPTION
**Pull request by OpenLedgerApp**
<h2>General</h2>
Closes #2813 

Set status to "Unknown member" if ChainStore.getAccountMemberStatus returns undefined

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by startailcoon** [comment]
According to bitsharesjs it returns null or undefined if account is not available. I think we should rather look on the root cause on why this is. Does it happen all the time, is it a timeout issue from the node etc?

https://github.com/bitshares/bitsharesjs/blob/46eecdf8517536b35b1917b96d375e3b92e1d756/lib/chain/src/ChainStore.js#L1055-L1057

```
    getAccountMemberStatus(account) {
        if (account === undefined) return undefined;
        if (account === null) return "unknown";
```

I also think that having an entry for `Unkown User` would confuse users even more.

**Comment by OpenLedgerApp** [comment]
@startailcoon, it's a timeout issue from the node. Maybe will be better if we will not show account row if account is not available(null or undefined)?

**Comment by sschiessl-bcp** [comment]
Yes, I would say if it's loading do not show the row item at all. If there is at least one still being loaded, if possible, show a loading indicator as the last (not clickable) item in the combobox

**Comment by abitmore** [comment]
Is it related to https://github.com/bitshares/bitshares-core/issues/1734?

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp I hided rows if account isn't availble
@abitmore no, it's not related

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp I hided rows if account isn't availble
> @abitmore no, it's not related

I think it's related to what abit said. Anyways, your solution is intended UX

**Comment by sschiessl-bcp** [comment]
Thank you.

I always feel that the 
`let account = ChainStore.getAccount(accountName);` usage is abusing the system. This should be done with a Promise (e.g. through FetchChainObject or any of the other promisified functions). I feel we should update this very central component to be properly promisified instead of hoping for re-renders.

Mergin this now, will open a new issue

**Pull request merged**
