### PR TITLE
Adding api.bitshares.info api node

### PR DESCRIPTION
**Pull request by brekyrself**
Added an API node located in North America, wss://api.bitshares.info

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Are you blocking http connections? I can't connect to http://api.bitshares.info or https://api.bitshares.info

**Comment by brekyrself** [comment]
> Are you blocking http connections? I can't connect to http://api.bitshares.info or https://api.bitshares.info

I had a dns mixup with the test server I am also setting up.  The API server should be backup in 24 hours once the DNS updates.

I have a hardware firewall allowing port 443 and UFW to allow HTTPS only.  This setup was working before the mix I caused the other day.

**Comment by sschiessl-bcp** [comment]
Still kaputt

**Comment by brekyrself** [comment]
> Still kaputt

I will close this for now and re-open once everything is back up and running.  Ran into some issues trying to do everything on ubuntu 22.04 instead of the tried and true 20.04.

**Comment by brekyrself** [comment]
API server back up and running @ wss://api.bitshares.info

**Pull request merged**
