### PR TITLE
add Winex gateway service

### PR DESCRIPTION
**Pull request by axin313**
We added Winex gateway service, now support HSR and ETC，Will support more coins.
please help me review the code.
thank you

### CODE REVIEW

**Comment by svk31** [comment]
I would like to see some more information about this gateway. Who's behind it, what's your goal etc?

**Comment by axin313** [comment]
Our team is from China's bitshares community and currently has eight members.
We have a lot of practical experience in exchange operation and blockchain related technology.
We have a close relationship with Committee Members bitcrab, abit and other members of the Chinese community.
Based on the research and study of the bitshares, it has developed a strong interest, and also wants to contribute to the promotion of bitshares in China, and also actively to expand the ecological construction of bitshares.
The acceptance gateway and the exchange winex.pro will continue to do more exploration and application.
our home page: https://www.winex.pro，You can browse the English version at the top right.

**Comment by svk31** [comment]
I tried merging this today but the rebase gets completely messed up for some reason, and it starts adding some old folders from the old app structure so I abandoned it. Please make sure you're working off the current staging branch and update the PR or create a new one which can be merged directly.

**Comment by axin313** [comment]
I'm sorry, I did the check. locale-zh.json clashes. I've settled the conflict. Please do it again.

**Pull request merged**
