### PR TITLE
Fix - Layout issues for various screen sizes

### PR DESCRIPTION
**Pull request by startailcoon**
# Small Fix
Fixes layout on Exchange when various screen sizes are used. 
Not tied to an issue.

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Hm. Bug in large screen
image

**Comment by startailcoon** [comment]
Let me review this again then. It's a bit tricky right there.

**Comment by sschiessl-bcp** [comment]
Any updates here?

**Comment by startailcoon** [comment]
Sorry for the delay. Here is a new commit to this PR that hopefully solves the issue of card arrangement. I've tested it against, hopefully, all possible variations.

**Comment by sschiessl-bcp** [comment]
Screen width ~1500
image

**Comment by sschiessl-bcp** [comment]
Between 1440 and 1568 screen size something weird is happening, rest looks sweet.
image

I suggest abandoning this size in favor of acting as if greater than 1568

**Comment by startailcoon** [comment]
I can't reproduce this. This is with the following display

- Order Book: Left (hidden)
- Form: Inline
- Grouped by default

bitshares-exchangelayout_size

- Order Book: Inline
- Form: Inline
- Grouped by default

bitshares-exchangelayout_size2

**Pull request merged**
