### PR TITLE
Issue 2570 - Cumulative Debt Column

### LINKED ISSUE #2570: [Keegan-lee][1] Add cumulative amount in collateral bids table
**Is your feature request related to a problem? Please describe.**
https://wallet.bitshares.org/#/asset/USD
Current collateral bids table:
image

It would be more convenient if there is a "cumulative debt" column, just like the order book:

image

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Keegan-lee**
<h2>General</h2>
Closes #2570

- Add cumulative debt column to Collatoral Bids table 

- Add required translations for new column

- Add debt summation logic

Screen Shot 2019-04-09 at 11 02 07 AM

### CODE REVIEW

**Comment by startailcoon** [comment]
Not sure if I like the extra column. Can't we have it as a total on the header instead, as we have on the order book?

image

**Comment by Keegan-lee** [comment]
Definitely can do this if needed. Waiting on sschiessl-bcp and abitmore for input.

**Comment by abitmore** [comment]
The extra column is exactly what I wanted. Thanks.

**Comment by startailcoon** [comment]
Great, thanks for the reply. My misunderstanding.

One idea though, can we have the cumulative debt value displayed somewhere on the Asset page?

My suggestion is under Settlement >> Reviving.

**Comment by sschiessl-bcp** [comment]
Forgot to hide header, fixed

**Pull request merged**
