### PR TITLE
#984: Enabled Buy/Sell widgets on Exchange.

### PR DESCRIPTION
**Pull request by TBAPI-0KA**
I only needed to enable Buy/Sell widgets on Exchange - somebody already wrote the code which asks for unlocking permission.

Since it's not a UI styling issue, tested only on Chrome/Windows.

### CODE REVIEW

**Comment by svk31** [comment]
This only enables one small part: the buy/sell form. notMyAccount is used in multiple places to disable parts of the exchange UI. If we're removing that, noyMyAccount and all uses of it should be removed completely.

**Comment by svk31** [comment]
#984 is the issue

**Comment by TBAPI-0KA** [comment]
@svk31 You're right - notMyAccount is also used on Market History, My Open Orders, and Borrow functions. However, this is the exact reason why I haven't removed its usage everywhere. Quoting @wmbutler from issue description: 
>  the buy/sell controls in the exchange.

> Let's start with the Exchange.

Should any other controls be enabled in the scope of this issue?

**Comment by TBAPI-0KA** [comment]
@svk31 Well, @gibbsfromncis showed me one specific case, after which I performed some investigation, and things with this `notMyAccount` variable you pointed out are much more complicated than it looks initially.

First of all, I didn't know that there's some kind of "impersonation" feature, so a user can see the dashboard as another user. That's why `notMyAccount` was created at all.

Going through codebase, it all ends in `getMyAuthorityForAccount` method of `app/stores/AccountStore.js`. For typical scenario, it should return the string "full" (or "partial" for shared accounts), and "none" in case that a user is impersonating somebody else.

However, I found a behavior which looks like a bug to me. "full" is returned correctly for cloud wallet, but it returns "none" for a local wallet. So, in fact, there's no check like "is account locked or not", and my changes enable widgets even for impersonated users, which is wrong.  On the other hand, keeping the old behavior doesn't allow to unlock widgets for cloud wallet users in case they aren't impersonated, but the account is locked.

The issue is that this method is widely used all over the app, and changes to it involves much more places than just these two widgets. So, I see two options here. If behavior for local wallets is correct, please explain me, why, because I don't know how correct solution should look like in this case. Otherwise, if this is a bug indeed, I offer the following path:
1. Create a separate issue to investigate, fix and test the bug, so local accounts also have authority for their account;
2. Make #984 dependant issue;
3. I'll fix both issues, in particular, by separating checks for account ownership and lock status of the account. The check for these widgets will be as before: `{disabled: notMyAccount }`, in other places, where controls should be still disabled - something like `{disabled: notMyAccount || isAccountLocked}`.

What do you think?

**Comment by abitmore** [comment]
Perhaps off topic, but what's `notMyAccount`? If you're going to disable some functionalities, please take a look at #1285.

**Comment by svk31** [comment]
You don't have to backtrack all the way to the AccountStore, all it's used for here is to determine whether actions should be disabled when you don't control an account. However, getMyAuthorityForAccount  does not work for cloud accounts until you log in, so they become disabled here. Just remove the variable in Exchange.jsx and remove the uses.

**Comment by TBAPI-0KA** [comment]
Done, please check.

**Pull request merged**
