### PR TITLE
Add Japanese translation for #1186

### PR DESCRIPTION
**Pull request by ahdigital**
For #1186
- Added Japanese translation file
- Updated other locales to include the language name
- Configured settings to recognise 'JA' ISO 639-1 code
- Updated flag file name to match ISO 639-1 code

### CODE REVIEW

**Comment by svk31** [comment]
There's a duplicate generate_new key on line 1443, please remove that then I'll merge the PR.

https://jsonlint.com/ is very handy for checking json file syntax.

**Comment by ahdigital** [comment]
> There's a duplicate generate_new key on line 1443

Of what file please? In locale-ja.json I have:

image

And in locale-en.json I have:

image

None of the other locale files have that many lines.

**Comment by svk31** [comment]
Yes that's the right file. There's another generate_new key a few lines further up.

**Comment by ahdigital** [comment]
Sorry long day.. I guessed you meant they were next to each other. Amendment submitted.

**Pull request merged**
