### PR TITLE
#1106 Order book: stack orders those prices are too close

### PR DESCRIPTION
**Pull request by ety001**
finish #1106 .

This is the preview.

[https://steemitimages.com/DQmXFJkVyVmBeR3VfcFKowyu8VRj4MTgSoN8hDF3rTmdMJg/stack-order.gif](https://steemitimages.com/DQmXFJkVyVmBeR3VfcFKowyu8VRj4MTgSoN8hDF3rTmdMJg/stack-order.gif)

### CODE REVIEW

**Comment by abitmore** [comment]
@ety001 please solve conflicts. BTW, may need to adapt to #1477 later. @svk31 @wmbutler perhaps merge this before starting working on #1477? I'm not sure how much more work is needed for merging.

**Comment by ety001** [comment]
@abitmore The conflict has been solved. I think #1477 should be merged first and then I'll resolve the conflicts between this PR and #1477 .

**Comment by svk31** [comment]
Ok, I'll look at this once #1477 has been merged.

**Comment by svk31** [comment]
Since the exchange redesign seems to be taking a while, I figure we can just merge this anyway. I have the conflicts fixed locally so you don't have to worry about that, I'm curious about how orders are grouped though. Using 1% grouping the top buy order disappears, is that working as intended? See the ungrouped and grouped screens below:

image

image

**Comment by ety001** [comment]
I think I found some bugs. I am fixing.

**Comment by ety001** [comment]
@svk31 The bug of ask orders precision has been fixed. Now it works.

**Comment by svk31** [comment]
Just tried it but the dropdown no longer has any options available so I can't activate it.

**Comment by abitmore** [comment]
@svk31 switch to a more recent API node? The dropdown should be auto-generated.

**Comment by svk31** [comment]
I'm using wss://eu.nodes.bitshares.ws. We're rejecting nodes without the orders_api activated so that shouldn't be an issue.

**Comment by ety001** [comment]
@svk31 I tried to run some commands on wss://eu.nodes.bitshares.ws and I got errors.

image

I think this node maynot the newest version.

**Comment by ety001** [comment]
@svk31 I checked the PR [#662](https://github.com/bitshares/bitshares-core/pull/662) and found this:

> new "grouped_orders" plugin enabled by default if `plugins` option is not configured

So I think some nodes maynot update new version or enable the grouped_orders plugin.

**Comment by ety001** [comment]
I wrote a script to detect which nodes have supported grouped_orders api.

[https://gist.github.com/ety001/a8534808f2951df0bad3eaab9ffd54a6](https://gist.github.com/ety001/a8534808f2951df0bad3eaab9ffd54a6)

This is the result for now.

```
[connect failed]  wss://japan.bitshares.apasia.tech/ws connect ECONNREFUSED 198.13.34.161:443
[X] wss://dexnode.net/ws
[X] wss://kc-us-dex.xeldal.com/ws
[support] wss://api.bts.mobi/ws
[connect failed]  wss://btsza.co.za:8091/ws connect ECONNREFUSED 41.185.20.18:8091
[connect failed]  wss://dex.rnglab.org certificate has expired
[X] wss://api.btsxchng.com
[support] wss://la.dexnode.net/ws
[connect failed]  wss://bitshares.nu/ws Unexpected server response: 404
[X] wss://api.bts.network
[support] wss://bitshares.openledger.info/ws
[X] wss://bitshares.crypto.fans/ws
[connect failed]  wss://us.nodes.bitshares.ws Unexpected server response: 503
[connect failed]  wss://bts.proxyhosts.info/wss write EPROTO 139918042516360:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:802:

[support] wss://blockzms.xyz/ws
[X] wss://node.market.rudex.org
[connect failed]  wss://eu.nodes.bitshares.ws Unexpected server response: 503
[support] wss://bts-api.lafona.net/ws
[X] wss://api.bts.blckchnd.com
[X] wss://api-ru.bts.blckchnd.com
[support] wss://api.bitshares.bhuz.info/ws
[support] wss://btsws.roelandp.nl/ws
[support] wss://bitshares-api.wancloud.io/ws
[support] wss://testnet.bitshares.apasia.tech/ws
[connect failed]  wss://sg.nodes.bitshares.ws Unexpected server response: 503
[X] wss://bit.btsabc.org/ws
[connect failed]  wss://testnet.nodes.bitshares.ws Unexpected server response: 503
[support] wss://node.btscharts.com/ws
[X] wss://node.testnet.bitshares.eu
[support] wss://btsfullnode.bangzi.info/ws
[support] wss://kimziv.com/ws
[X] wss://ws.gdex.top
[connect failed]  wss://bts-seoul.clockwork.gr/ Unexpected server response: 503
[support] wss://ws.hellobts.com/
[support] wss://eu.openledger.info/ws
[X] wss://crazybit.online
[X] wss://api.btsgo.net/ws
[support] wss://bitshares.cyberit.io/
[support] wss://bts.open.icowallet.net/ws
[X] wss://bitshares.dacplay.org/ws
[support] wss://openledger.hk/ws
[X] wss://api.bts.ai/
[X] wss://ws.winex.pro
[support] wss://bitshares.bts123.cc:15138/
[support] wss://bts.to0l.cn:4443/ws
[connect failed]  wss://ws.gdex.io Unexpected server response: 502
[connect failed]  wss://freedom.bts123.cc:15138/ WebSocket was closed before the connection was established
```

**Comment by startailcoon** [comment]
**Question**: How does this look in the vertical order book where we have no headers?

**Comment by ety001** [comment]
@startailcoon This is the preivew animation:  https://steemitimages.com/DQmXFJkVyVmBeR3VfcFKowyu8VRj4MTgSoN8hDF3rTmdMJg/stack-order.gif

**Comment by ety001** [comment]
@svk31 Do we have a plan to merge this branch?

**Comment by svk31** [comment]
Yes, I wasn't sure in the end whether to merge it before or after the exchange refactoring, but if it's ready now I think I'll just merge it.

**Comment by startailcoon** [comment]
Would be perfect to merge this now and I can hopefully find a good way to use it on the new Exchange design.

**Comment by ety001** [comment]
@svk31  Hi, I wander to know when to pay bounties.
My bitshares account is [ety001.worker](https://wallet.bitshares.org/#/account/ety001.worker).

**Pull request merged**
