### PR TITLE
Issue-2657. add json modal for all blockchain operations

### LINKED ISSUE #2657: [2] Add raw json for operations and objects
**Is your feature request related to a problem? Please describe.**
image

In some cases it's not clear what the ops means.
Pages that I thought of:
- [x] block explorer
- [x] account activities
- [x] proposed proposals
- [x] transaction confirmation page

**Describe the solution you'd like**
Add a link so the nerds can check the raw json.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by OpenLedgerApp**
<h2>General</h2>
Closes #2657 

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at 
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

image

new modal window with json
image

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Please rebase, and make it that it appears more seamless in the headline

Display the text "RAW" on the right side of the headline
image

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp, done.
image

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp, done.
> image

Excellent!

**Comment by startailcoon** [comment]
Not sure I like the placement of just "RAW" on the side. It's not descriptive at all for users, and it looks weirdly placed. 

What about using an icon like this?

image

**Comment by sschiessl-bcp** [comment]
I can create an icon and try it with a screen (if OL is not too keen on doing that in the scope of this issue)

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp it will look like this

image

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp it will look like this
> 
> image

I like it! I'd suggest to put the icon immediately behind the title (with a space) and not in the right column, then we have a winner!

**Comment by abitmore** [comment]
I like icon+text more than an icon only. The text can be "show raw json" for clearer.

**Comment by sschiessl-bcp** [comment]
> I like icon+text more than an icon only. The text can be "show raw json" for clearer.

And leave it in the right column?

**Comment by abitmore** [comment]
> And leave it in the right column?

I'm fine.

Just came up with an idea: we can even generate a QR for the json.

**Comment by sschiessl-bcp** [comment]
> > And leave it in the right column?
> 
> I'm fine.
> 
> Just came up with an idea: we can even generate a QR for the json.

To allow a mobile app to scan & sign & broadcast?

I wanted to also allow the ref UI to take a json-string representation of a tx and do finalize, sign & broadcast.

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp could you please clarify: icon+text "show raw json" should be in the right column?

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp could you please clarify: should icon+text "show raw json" be in the right column?

Please make a good suggestion :)

**Comment by OpenLedgerApp** [comment]
image

**Comment by startailcoon** [comment]
Looks much better now. Good work

**Pull request merged**
