### PR TITLE
#1673 - Allow proposal_delete operation

### LINKED ISSUE #1673: [2.5][kapeer42] Permanently reject a proposal
**Is your feature request related to a problem? Please describe.**
There is a "proposal_delete_operation" in the core, although a little buggy when using on multi-sig accounts, it would be quite easy and useful for normal accounts (e.g. to fight scams/phishing). Especially, as of writing, on BitShares mainnet, the required fee is zero.

**Describe the solution you'd like**
Able to permanently reject a proposal. 

**Describe alternatives you've considered**

**Additional context**
See https://bitsharestalk.org/index.php?topic=26782.msg319803#msg319803.

### PR DESCRIPTION
**Pull request by kapeer42**
:cloud_with_rain: It's raining PRs :cloud_with_rain: 

Closes #1673 and #1864 

deletable-proposal-demo
delete-proposal-transaction-demo
deleted-proposed-transaction-demo

### CODE REVIEW

**Comment by abitmore** [comment]
Good job. IMHO best show the proposal ID in the description.

**Comment by kapeer42** [comment]
Agreed, on it

**Comment by kapeer42** [comment]
I only show the proposal id not the full object id, tell me if I should change it to the full id or change the formatting.
proposal-id-demo

**Comment by abitmore** [comment]
@kapeer42 look good to me. Thanks.

**Comment by startailcoon** [comment]
I think an update should write out the new proposal object, as you can't see what have changed.

The delete may not require the object to be printed out, but could be of interest as the original proposal may be so old it's not visible in the history of transactions.

**Comment by abitmore** [comment]
> I think an update should write out the new proposal object, as you can't see what have changed.

I think the description should be something like this:
* `aaa` (read: the fee payer) updated proposal `#xxx`:
  * added `owner approval` of `aaa`;
  * removed `active approval` of `aaa`;
  * added `key approval` of `BTS7xxxxxxPub`

As to the object, since it's not in the operation, it's unable to be printed in history.

**Comment by kapeer42** [comment]
On it, more hours would be welcomed indeed.

**Comment by startailcoon** [comment]
Great work 👍

Lets track the extra hours for the proposed changes in a new issue.

**Comment by kapeer42** [comment]
Last commit is for https://github.com/bitshares/bitshares-ui/issues/1673#issuecomment-422367284

**Comment by abitmore** [comment]
Actually I think the "delete" word in UI is not very good, since it's a bit confusing. How about change it to "permanently reject" as described in the issue?

**Comment by sschiessl-bcp** [comment]
I agree and adjusted the wording.

**Pull request merged**
