### PR TITLE
#2602. Include "Remaining Settlement Volume", "Max Settlement Volume" in Settlement Modal

### LINKED ISSUE #2602: [1.5][MikhailKavalenka] Include "Remaining Settlement Volume" in Settlement Modal
When a user wants to settle a specific volume, the network has a limit per maintenance period that is allowed for the asset to be settled. This should be included in the information for the user _if_ the limit is reached.

- [ ] Remaining settleable volume
- [ ] Notify user an estimated delay based on variables `Max. settlement volume each maintenance period`, `Already settled supply` and `Remaining settleable volume`.

Also part of https://github.com/bitshares/bitshares-ui/issues/1081

### PR DESCRIPTION
**Pull request by OpenLedgerApp**
<h2>General</h2>
Closes #2602 

<h2>General</h2>
lease make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at 
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [x] Light
- [x] Midnight

When user inputs more than remaining settlement volume this info block is shown
image

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Do you have the estimate added somewhere? I couldnt see it. It could be added as additional text in the top notification.

The estimation would be `settlement delay + floor(requestedVolume / maxSettlementVolume)*maintenance interval`

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp done

**Comment by sschiessl-bcp** [comment]
I see that you merged the current develop branch, but it seems that the formatting is still different. Do you have any local formatting enabled?

https://github.com/OpenLedgerApp/bitshares-ui/commit/40c17d71f6635a530ba60b0b0ce17d7415ec5f11

**Comment by sschiessl-bcp** [comment]
Where was the estimation added now? It should be visible in the SettleModal before pushing the tx.

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp done. Now estimation is placing in the SettleModal.
image

**Comment by sschiessl-bcp** [comment]
Super, thanks!

How do you judge the needed hours vs the offered bounty? The misunderstanding certainly took some of that ...

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp Thanks for your question. I suppose we spent about 3hours for this task.

**Pull request merged**
