### PR TITLE
New faucet according to infrastructure worker proposal

### PR DESCRIPTION
**Pull request by xeroc**
This is the onboarding faucet.

Stats and settings can be found here:

* https://bitshares.eu/referral/onboarding/onboarding.bitshares.foundation

### CODE REVIEW

**Comment by svk31** [comment]
So just to make sure we don't get lots of complaints like last time, it's safe to just replace the old one with this one? Referrals will work the same?

**Comment by btsfav** [comment]
@svk31 could you provide a testversion, if you go time?

**Comment by svk31** [comment]
Yes I will provide one that you can test over the weekend.

**Comment by xeroc** [comment]
@svk31 if you try register an account with the name starting with `test-faucet` (e.g. `test-faucet3253252`) the faucet will not actually register the account but do everything as usual and return the raw transaction to you ..

**Comment by xeroc** [comment]
> So just to make sure we don't get lots of complaints like last time, it's safe to just replace the old one with this one? Referrals will work the same?

Referals should work the same .. i did quite some tests on the new "selection" algorithm to distinguish different modes of operation

**Pull request merged**
