### PR TITLE
Resolve Issue 47 - Ensure primary asset shows up in balance calculations

### PR DESCRIPTION
**Pull request by calvinfroedge**
Resolves [issue 47](https://github.com/bitshares/bitshares-ui/issues/47).

The problem was the loop was skipping setting assetValues (used to display the drop down values) for the primary asset.

I just removed the if condition. Here is screenshot showing correct values:

asset-value-calc

### CODE REVIEW

**Comment by svk31** [comment]
That `if` condition merely checks if a conversion is necessary or not. So if you want to display the value in USD and the current balance is USD, you just add it to the total, you don't need to use _convertValue

**Comment by svk31** [comment]
I still don't see how this PR changes or fixes anything, the behaviour is the same as before.

**Comment by calvinfroedge** [comment]
@svk31 Behavior is not the same as before. Let's walk through old code.

```
        // Balance value
        balances.forEach(balance => {
            if (balance.asset_id === toAsset.get("id")) {
                totalValue += balance.amount;
            } else {
                let fromAsset = assets[balance.asset_id];
                if (fromAsset) {
                    let eqValue = this._convertValue(balance.amount, fromAsset, toAsset, marketStats, coreAsset);
                    totalValue += eqValue;
                    assetValues = this._assetValues(assetValues, eqValue, fromAsset.get("id"));
                }
            }
        });
```

The dropdown / tooltip values are displayed from `assetValues`. In the case where `toAsset` is the same as the current balance in `balances` being iterated over, it is skipped and not added to `assetValues`, only to the total value:

```
            if (balance.asset_id === toAsset.get("id")) {
                totalValue += balance.amount;
            }
```

The change I made removes the if condition so that regardless of whether or not the asset is the same as the format being converted TO (i.e. bts, usd, whatever the preferred unit is), the value is always added to both total value AND asset value. So it's not the same as before as you can see in screenshot which I took.

**Comment by svk31** [comment]
Ok I see the issue now, the assetValues update was missing in the first part so it could've been solved by just adding this line to the first if condition:

`assetValues = this._assetValues(assetValues, balance.amount, toAsset.get("id"));`

**Pull request merged**
