### PR TITLE
Revise and update Chinese translation

### PR DESCRIPTION
**Pull request by HarukaMa**
**Work in progress**

- [x] Revise existing translations
- [x] Reorder to match English translation file
- [x] Add new translations recently added 
- [x] Lint
- [x] Unify terminology
- [x] Proper multi-language readme
- [x] <s>Extra: Help (if I still have time before milestone ddl)</s> It seems that the help inside DEX will be redesigned, so I'll postpone this,

The simplified Chinese translation is outdated, some sentences are not natural, and there are some critical translation errors.

Multiple commits may exist during the work, and will be squashed afterwards.

Request for comment: <s>Should we have links to, like bitshares.org, bitsharestalk or github repo, in reference wallet UI? Current translation even includes a qq group number, which I think should not exist in reference wallet. I plan to remove those.</s> Seems `intro_text_2` to `intro_text_4` is no longer used in current design, they are effectively removed already.

Question: <s>why there are Chinese translation in readme.md of the repo? I think it would be better to keep every language separate and provide links to them in English readme. The current version only makes the readme harder to read for both languages' users.</s> I'm doing this regardless. Seems much cleaner.

### CODE REVIEW

**Comment by wmbutler** [comment]
There is a worker proposal on the DEX which looks like it will address the financial side of this so I won't assign a bounty to this, but i will add it to the 180115 milestone.

**Comment by HarukaMa** [comment]
It seems that worker is for public relations side instead of DEX side (which is sad I think) as stated in the proposal :

> Translating publication material (advertising, news, etc.) to Chinese

while the translations on DEX is also important now for the reference wallet users.

Also, responses to the question and RFC in the original post is welcomed as I'm still unsure of the view of project members on those points...

**Comment by HarukaMa** [comment]
Main work is done, but there may still be community feedback from bitsharestalk in following days so there is no need to merge right away.

**Comment by svk31** [comment]
Is this OK to merge now?

**Comment by HarukaMa** [comment]
Community feedbacks now is mainly about help part, but I plan to do that part after the help section is renewed. I think this PR could be merged now.

@wmbutler That work proposal has failed to pass and will expire soon. Would you reconsider?

**Pull request merged**
