### PR TITLE
#1529 Expiration Time display in Open Orders

### PR DESCRIPTION
**Pull request by happyconcepts**
Opted for using `time_format` from utils.js since it's already imported; manual integration testing passed.

### CODE REVIEW

**Comment by startailcoon** [comment]
@happyconcepts @svk31 this merge gives me "Invalid Date" errors.

## With the PR
bitshares-dateissues

## Without the PR
bitshares-dateissues_2

**Comment by sschiessl-bcp** [comment]
Looks fine on current develop branch
image

**Comment by startailcoon** [comment]
@sschiessl-bcp you'r looking on Market Trades, not Open Orders.

bitshares-dateissues_3

**Comment by sschiessl-bcp** [comment]
image

**Comment by svk31** [comment]
I get same as @sschiessl-bcp , looks fine here.

**Comment by svk31** [comment]
Ok I can reproduce it using Firefox, Chrome is fine

**Pull request merged**
