### PR TITLE
#2783. fix for price while withdrawing

### LINKED ISSUE #2783: [0.5] Wrong price while withdrawing
**Describe the bug**
It seems that entering an amount in the "withdraw" dialog updates the BTS price of the asset to withdraw in the background. This price update seems to handle precision wrongly.

**To Reproduce**
1. Go to Dashboard / Portfolio
2. Click on e. g. OPEN.BTC -> Withdraw
3. Enter amount to withdraw
4. The background dashboard updates the price of OPEN.BTC. New price is too high by a factor of 1000.

**Expected behavior**
Nothing (or display correct price)

**Screenshots**
Screenshot_20190617_091701

(OPEN.BTC price is 141M not 141K, see GDEX.BTC for comparison)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium
 - Version 74.0.3729.157 (openSUSE Build) (64-Bit)

### PR DESCRIPTION
**Pull request by OpenLedgerApp**
<h2>General</h2>
Closes #2783 

Сommented code, which changed asset precision and was used in WIthdrawModalNew component for estimated value block. But this block was commented at 28.02.2018 by Calvin Froedge "Remove estimated value filed". If this block isn't used , part of the code can be removed.

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Can you please give me precise steps how you have reproduced the problem described in the issue? I can't figure it out

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp yes sure.
1. Go to Dashboard / Portfolio
2. Click on e. g. OPEN.BTC -> Withdraw
3. Enter amount to withdraw (I enter a lot of zero values and the price of OPEN.BTC is updated in a few seconds)
4. The background dashboard updates the price of OPEN.BTC

image

**Comment by sschiessl-bcp** [comment]
Please the precise step with the exact entered amount and possible account 
you used for it

Am 24. Juni 2019 16:39:39 schrieb OpenLedger <notifications@github.com>:

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp I use wallet model. There is no exact entered amount, it's always different value, updating doesn't depend on it.
The price updates on condition when assets(fromAsset, toAsset = "BTS", precision = 5) have different precision and when variable allMarketStats updates in the EquivalentPrice component from MarketStore.

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp I use wallet model. There is no exact entered amount, it's always different value, updating doesn't depend on it.
> The price updates on condition when assets(fromAsset, toAsset = "BTS", precision = 5) have different precision and when variable allMarketStats updates in the EquivalentPrice component from MarketStore.

I did not see the picture you provided in the second to last comment, apologies (was on the phone). Can reproduce it now. 

Have you found any clue what the code you commented out was designed for?

**Comment by sschiessl-bcp** [comment]
Merged, but please comment on my question above

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp, this block is used to get marketStats, which used to calculate estimatedValue.

if (quantity && fromAsset && toAsset) {
                estimatedValue =
                    quantity *
                    MarketUtils.getFinalPrice(coreAsset, fromAsset, toAsset, marketStats, true, true
                    );
                if (precisionDifference > 0) {
                    //Need to compensate for different precisions between currencies
                    estimatedValue = estimatedValue * Math.pow(10, precisionDifference);
            } //No need to compensate for precision difference < 0
}

But block with estimatedValue was commented  at 28.02.2018 by Calvin Froedge "Remove estimated value filed"
{/*ESTIMATED VALUE*/}
                        {/*
                (assetAndGateway || quantity) && !isBTS ?
                <div>
                <label className="left-label"><Translate content="modal.withdraw.estimated_value" /> ({preferredCurrency})</label>
                <ExchangeInput value={userEstimate != null ? userEstimate : estimatedValue} onChange={this.onEstimateChanged.bind(this)} onFocus={onFocus} onBlur={onBlur} />
                </div> :
                null
            */}

**Pull request merged**
