### PR TITLE
 Add CryptoSudo Gateway

### PR DESCRIPTION
**Pull request by cryptosudo**
CryptoSudo is the developing and education ecosystem on the basis of Blockchain Technology.

We believe that the developers are critical value to Blockchain Technology. Our another goal is to bring new developers to this sector and help existing developers do their jobs well. We will introduce an online and free training platform about the cryptography and software languages which are basis of this technology. And we will spread this platform to masses.

Our ecosystem will be a central development and education platform for Blockchain Technology, supported by SUDO crypto currency.

We have talked with several exchanges & we want you to know it never ends with listing. Wallet updates, forks etc have costs. As BTC goes down listing fees goes up. Projects exhaust their resources & it become impossible to develop anymore. Unfortunately it has become a zero-sum game.

 We need more options not just for us but all crypto ecosystem. Whats the point giving ridiculous amont of premine to hands of exchanges to dump anytime on retail investors or spending our resources just for listing? So we decided to instead of paying someone to list us just do our job for ourselves.

We are officially started to work on our DEX. We are planning to launch end of January. We will get listed on our own exchange.

Website: https://cryptosudo.eu/
Block Explorer: https://cryptosudo.online/
Official Pool: https://cryptosudo.site/
Github: https://github.com/cryptosudo/sudo
Assets: https://github.com/cryptosudo/sudo-assets
Whitepaper: https://cryptosudo.eu/CryptoSudo-Whitepaper.pdf
Wallets: https://github.com/cryptosudo/sudo/releases/
Bitcointalk Ann: https://bitcointalk.org/index.php?topic=5067051
Twitter: https://twitter.com/cryptosudosu
Reddit: https://www.reddit.com/user/CryptoSudo
Medium: https://medium.com/@cryptosudo

### CODE REVIEW

**Comment by Kennybll** [comment]
Your locale's have merge conflict in them (the <<< head parts). Also [this](https://github.com/bitshares/bitshares-ui/pull/2365/files#diff-afea32c2b6ea385a563f120e84cb18f1R1066).

**Comment by sschiessl-bcp** [comment]
Please contact me via telegram @sschiessl

**Comment by cryptosudo** [comment]
I couldn't reach you. My Telegram Username is @cryptosudosu

**Comment by sschiessl-bcp** [comment]
Please let me know once you are up and running and we chat again.

**Comment by cryptosudo** [comment]
I am working on it. I will contact with you until 1 February 2019. Thanks.

**Comment by sschiessl-bcp** [comment]
Closing this, reopen if interested again

**Pull request closed without merging**
