### PR TITLE
Issue #167 contact list

### PR DESCRIPTION
**Pull request by efork**
Feature  #167.  Renamed "Follow" to "Add contact" and created new "Contact" tab.  First pull request.  Let me know if I missed the mark in any way.

### CODE REVIEW

**Comment by svk31** [comment]
I'm not sure it's a great idea to replace the existing follow functionality with contacts. The way it works currently it lets you monitor other accounts, whether they're your own from different wallets or someone else's. If contacts are added to this you'd potentially be monitoring lots of accounts, triggering unecessary data fetching. This really only applies to the dashboard page however, so I suppose it can be worked around.

**Comment by efork** [comment]
Thank you for the feedback.  I believe I hit the task as currently spec'd, really just a terminology change that I tried to do as lightly as possible.  If this missed the mark let me know what direction you would like to go.  I can also grab any related tasks associated with this one (#781, #716, etc) to avoid any merge issues if thats a concern.  Love what you guys are doing and would love to grab an oar.

**Comment by svk31** [comment]
I'll merge it since I don't think it's really a big deal that we're reusing follows, but we need to keep in mind the original intention of follows and most likely remove followed accounts from the recent transactions list in the original Dashboard page.

**Comment by svk31** [comment]
Actually using the contacts for transfers still remains to be done but we can do that in a separate issue I guess.

**Pull request merged**
