### PR TITLE
Issue 1707 - "Settle Backing Asset" Translation Issue

### PR DESCRIPTION
**Pull request by startailcoon**
# Resolves Issue #1707 

Settle Backing Asset properly displayed
- Removes hardcoded value 'BTS'

bitshares-backingassetsettle

### CODE REVIEW

**Comment by abitmore** [comment]
Why didn't use the 'bit' prefix for XCD nor USD?

**Comment by startailcoon** [comment]
That's a very good question. XCD didn't have it from before and didn't think on it. Of course it should have the bit prepended to the name.

**Comment by startailcoon** [comment]
`bit` prepended to true bit Assets.

bild

**Comment by startailcoon** [comment]
I will supply a fix for this in a few days

**Comment by startailcoon** [comment]
Fixed bitAsset prefix issues.
Also fixes dynamic settle hours. Asset `GRIDCOIN` has 168 hours to settle.

bild

**Comment by startailcoon** [comment]
@svk31 ready for merging

**Comment by abitmore** [comment]
@startailcoon just want to confirm one thing: if an asset is global settled, force-settlement will be executed immediately, but not after X hours. Is this logic coded to the tool tip? E.G. check bitGOLD.

**Pull request merged**
