### PR TITLE
вывод средств

### PR DESCRIPTION
**Pull request by Igoor18**
не могу вывести BTC

### CODE REVIEW

**Comment by allfory0u** [comment]
> 
> 
> не могу вывести BTC
> 
> 

С этой проблемой обращайтесь в службу поддержки Crypto-Bridge:
https://t.me/cryptobridgeofficial
support@crypto-bridge.org
https://discord.gg/A2hrhHh

**Comment by allfory0u** [comment]
И для вопросов (касающихся wallet.bitshares.org) используйте пожалуйста Issue, а не Pull requests. Спасибо.

**Comment by sschiessl-bcp** [comment]
Thank you @allfory0u for responding. @Igoor18, what he said :)

**Comment by SergioToro-maker** [comment]
A similar problem with the conclusion BTC, and on the site Crypto-Bridge the support service in the ticket I opened does not respond to my request.
Today is December 8th and they close December 15th ..
How can you help? What do you advise?
Sounds like a scam

image

The support service also recommends that if you encounter problems, contact:
 https://github.com/CryptoBridge/cryptobridge-ui/issues

image

**Comment by sschiessl-bcp** [comment]
Seems like you need a couple of BTS to pay for transaction fee. You can come to Telegram channel @btswallethelp

**Comment by SergioToro-maker** [comment]
Thank you Stefan!
The problem has already been solved.
Bitcoins withdrew safely.

P.S. the mistake was on my part, sorry

**Pull request closed without merging**
