### PR TITLE
Issue 2543 - Full Export & Modal

### LINKED ISSUE #2543: [5][Keegan-lee] Account activities: Refine export function
**Is your feature request related to a problem? Please describe.**
The export feature is not obvious enough.
image

**Describe the solution you'd like**
Add text.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Keegan-lee**
<h2>General</h2>
Closes #2543 
- Add modal on export button click
- Add textbox for es endpoint
- Add button for coinbase export
- Add button for full/raw export
- Add functionality for raw export
- Externalize export functionality into class
- Add English translations for new UI

## Testing
Go to Activity tab, click export, and test both Coinbase and Full Report

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [x] Opera
- [x] Firefox
- [x] Safari

<h2>User interface changes</h2>

- [x] Dark
- [x] Light
- [x] Midnight

Screen Shot 2019-04-05 at 10 36 38 AM
Screen Shot 2019-04-05 at 10 36 44 AM

### CODE REVIEW

**Comment by startailcoon** [comment]
Based on your screenshot, the export icon is still not very explaining, which was one of the criteria for the issue.

**Comment by Keegan-lee** [comment]
Screen Shot 2019-04-07 at 9 52 28 PM

Yes, I missed that part. See the modification.

**Comment by sschiessl-bcp** [comment]
Please add two exemplatory exports in this issue

**Comment by Keegan-lee** [comment]
[exports.zip](https://github.com/bitshares/bitshares-ui/files/3054516/exports.zip)

Exports Included. 

For the raw export, I decided to have the entire row, (array of operation and raw operation) on each line. When importing CSV into a parser, the delimiter is the newline character instead of a comma, because the raw JSON contains many commas that we don't want the parser to split the data on.

**Comment by sschiessl-bcp** [comment]
How was your feeling on the estimated hours and actually spent hours? BitShares may have a steep learning curve

**Comment by atlantic-blockchain** [comment]
> How was your feeling on the estimated hours and actually spent hours? BitShares may have a steep learning curve

I thought it was fine actually. Not tough at all. The estimated hours was almost exactly the amount of hours I spent. It was a good estimation.

**Comment by Keegan-lee** [comment]
> How was your feeling on the estimated hours and actually spent hours? BitShares may have a steep learning curve

It was good actually. The estimate was right around the amount of time I spent working on it. There wasn't much of a learning curve, I'm already reasonably familiar with the tech. Looking forward to more tickets.

**Pull request merged**
