### PR TITLE
2870 portfolio price column invertible

### LINKED ISSUE #2870: Portfolio Price (BTS) column invertible
**Is your feature request related to a problem? Please describe.**
The Price (BTS) column in the Portfolio tab does not support inverting the price by click, like in Open Orders

**Describe the solution you'd like**
Make column clickable to invert price.

### PR DESCRIPTION
**Pull request by react-cat**
<h2>General</h2>
Closes #2870 

Add Inverted Price column to portfolio table and add sort function for that column.

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by startailcoon** [comment]
@react-cat can you add some screens?

**Comment by react-cat** [comment]
@startailcoon Sure 
AwesomeScreenshot-localhost-account-react-cat-2019-08-02_3_17 (2)

AwesomeScreenshot-localhost-account-react-cat-2019-08-02_3_17 (1)

AwesomeScreenshot-localhost-account-react-cat-2019-08-02_3_17

Also there is a bug that causes header to be in two rows except one, but as I see, it appears not because of changes that I made. Logic that should make it be in one row is already implemented, but for some reason doesn't work. I will later create a new issue about it.

**Comment by startailcoon** [comment]
It's a long title, so better have it on two rows to not bloat the table to much in width. There are others that are wider as well.

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/issues/2870#issuecomment-519548315

**Pull request closed without merging**
