### PR TITLE
#1543

### PR DESCRIPTION
**Pull request by dot5enko**

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Settlement price does not show for me, can you please check?

image

**Comment by dot5enko** [comment]
@sschiessl-bcp i don't know how to test it with ASDFB or ASDFUSDA. Perhaps testnet just lacks some data and the settle price is 0 (cause settlement block label is present on the header as you can see)? 
Can we test it on the mainnet with pairs that really have positive settlement price? cause i've removed condition which could cause issues mentioned in #1543

**Comment by dot5enko** [comment]
@sschiessl-bcp yup, i see. Will fix it asap

**Comment by dot5enko** [comment]
@sschiessl-bcp fixed. Check please

**Comment by sschiessl-bcp** [comment]
If I may, please use branch names a la "1543_MarketPage" in the future instead of simply the number "1543". This helps git to not confuse it with commits.

**Pull request merged**
