### PR TITLE
#2789. limit a number of updates for HelpContent component

### LINKED ISSUE #2789: [1] missing path 'assets/BTS' for locale 'ru'
**Describe the bug**
Russian locale hat issues and hung interface

**To Reproduce**
1. Go to settings
2. Switch it to russian
3. Go to Инфопанель (Dashboard)-> Портфель (Portfolio) -> BTS

**Expected behavior**
it must show information like on EN locale

**Screenshots**
photo_2019-06-18_00-30-02
photo_2019-06-18_00-30-17
photo_2019-06-18_00-30-31

**Desktop (please complete the following information):**
 - OS: mac os 10.14.5 (18F132)
 - Browser crome Version 74.0.3729.169 (Official Build) (64-bit)
 - Version 94497cd436da4955cd1831421a473c3fd2599e30

**Additional context**
`app.34d8d72b5e00aa405b59.js:1 missing path 'assets/BTS' for locale 'ru' help files, rolling back to 'en'
n @ app.34d8d72b5e00aa405b59.js:1
console.warn @ app.34d8d72b5e00aa405b59.js:1
value @ app.34d8d72b5e00aa405b59.js:1
Bi @ vendor.78dfe2a401cbe42d67c9.js:148
Ni @ vendor.78dfe2a401cbe42d67c9.js:148
da @ vendor.78dfe2a401cbe42d67c9.js:148
ha @ vendor.78dfe2a401cbe42d67c9.js:148
Ga @ vendor.78dfe2a401cbe42d67c9.js:148
qa @ vendor.78dfe2a401cbe42d67c9.js:148
Ka @ vendor.78dfe2a401cbe42d67c9.js:148
Ua @ vendor.78dfe2a401cbe42d67c9.js:148
ga @ vendor.78dfe2a401cbe42d67c9.js:148
enqueueSetState @ vendor.78dfe2a401cbe42d67c9.js:148
b.setState @ vendor.78dfe2a401cbe42d67c9.js:140
t @ vendor.78dfe2a401cbe42d67c9.js:32
(anonymous) @ vendor.78dfe2a401cbe42d67c9.js:32
Promise.then (async)
n._loadModule @ vendor.78dfe2a401cbe42d67c9.js:32
n.componentWillMount @ vendor.78dfe2a401cbe42d67c9.js:32
li @ vendor.78dfe2a401cbe42d67c9.js:148
Ni @ vendor.78dfe2a401cbe42d67c9.js:148
da @ vendor.78dfe2a401cbe42d67c9.js:148
ha @ vendor.78dfe2a401cbe42d67c9.js:148
Ga @ vendor.78dfe2a401cbe42d67c9.js:148
qa @ vendor.78dfe2a401cbe42d67c9.js:148
Ka @ vendor.78dfe2a401cbe42d67c9.js:148
ns @ vendor.78dfe2a401cbe42d67c9.js:148
Ln @ vendor.78dfe2a401cbe42d67c9.js:148
app.34d8d72b5e00aa405b59.js:1 missing path 'assets/BTS' for locale 'ru' help files, rolling back to alt_path 'assets/Asset'`

multiple errors 

`app.34d8d72b5e00aa405b59.js:1 missing path 'assets/BTS' for locale 'ru' help files, rolling back to 'en'
n @ app.34d8d72b5e00aa405b59.js:1
console.warn @ app.34d8d72b5e00aa405b59.js:1
value @ app.34d8d72b5e00aa405b59.js:1
Bi @ vendor.78dfe2a401cbe42d67c9.js:148
Ni @ vendor.78dfe2a401cbe42d67c9.js:148
da @ vendor.78dfe2a401cbe42d67c9.js:148
ha @ vendor.78dfe2a401cbe42d67c9.js:148
Ga @ vendor.78dfe2a401cbe42d67c9.js:148
qa @ vendor.78dfe2a401cbe42d67c9.js:148
Ka @ vendor.78dfe2a401cbe42d67c9.js:148
Ua @ vendor.78dfe2a401cbe42d67c9.js:148
ga @ vendor.78dfe2a401cbe42d67c9.js:148
enqueueSetState @ vendor.78dfe2a401cbe42d67c9.js:148
b.setState @ vendor.78dfe2a401cbe42d67c9.js:140
t @ vendor.78dfe2a401cbe42d67c9.js:32
(anonymous) @ vendor.78dfe2a401cbe42d67c9.js:32
Promise.then (async)
n._loadModule @ vendor.78dfe2a401cbe42d67c9.js:32
n.componentWillMount @ vendor.78dfe2a401cbe42d67c9.js:32
li @ vendor.78dfe2a401cbe42d67c9.js:148
Ni @ vendor.78dfe2a401cbe42d67c9.js:148
da @ vendor.78dfe2a401cbe42d67c9.js:148
ha @ vendor.78dfe2a401cbe42d67c9.js:148
Ga @ vendor.78dfe2a401cbe42d67c9.js:148
qa @ vendor.78dfe2a401cbe42d67c9.js:148
Ka @ vendor.78dfe2a401cbe42d67c9.js:148
ns @ vendor.78dfe2a401cbe42d67c9.js:148
Ln @ vendor.78dfe2a401cbe42d67c9.js:148
app.34d8d72b5e00aa405b59.js:1 missing path 'assets/BTS' for locale 'ru' help files, rolling back to alt_path 'assets/Asset'`

### PR DESCRIPTION
**Pull request by OpenLedgerApp**
<h2>General</h2>
Closes #2789 

This issue was reproduced on build version only. Page was crashed because Maximum update depth was exceeded. The similar issue was on openledger, but updating wasn't so fast, therefore page wasn't crashed. I added PureComponent to limit a number of updates. I also added and tested it on https://dev.openledger.info/asset/BTS/. I guess it will help for bitshares build version.
https://reactjs.org/docs/error-decoder.html/?invariant=185

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [x] Check for unused code
- [x] No unrelated changes are included
- [x] None of the changed files are reformatting only
- [x] Code is self explanatory or documented
- [x] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Do you have a reference how PureComponent limits amount of updates?

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp https://reactjs.org/docs/react-api.html#reactpurecomponent

**Comment by sschiessl-bcp** [comment]
Not sure that is what was needed here to treat the cause. I think that maybe the` [# sometext]` markers in the .md file broke (maybe also translated accidently)?

Could you check that please?

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp Yes, you are right, some markers was translated.

**Pull request merged**
