### PR TITLE
SendModal - Close once 'Confirm' is clicked in the Transaction dialog.

### LINKED ISSUE #945: [1][pnomolos] Remove Send modal immediately after clicking confirmation
After Accepting the confirmation modal, we should remove the send modal behind it. In cases where the node is slow to respond, this creates a very confusing situation for the user because the confirmation screen has gone away but the original send modal is still in place.

Upon clicking confirm:

- [ ] Close the original send modal
- [ ] Then close the confirm modal

send

### PR DESCRIPTION
**Pull request by pnomolos**
Was tricky due to some async issues, but this should fix #945.

### CODE REVIEW

**Comment by svk31** [comment]
Where does PubSub come from? Re my comment in the issue, I think Bill made this overly complicated, we should just close it as soon as the user clicks send, if it's a valid transfer.

**Comment by pnomolos** [comment]
OK I’ll make those changes. PubSub is what ZfApi uses internally, but since
that’s vendored I couldn’t add publishAsync to it.

**Comment by pnomolos** [comment]
@svk31 Changes made.  Also prevented 'Send' from activating if the to and from accounts are the same.

**Comment by wmbutler** [comment]
Sorry if I overcomplicated that.

**Comment by svk31** [comment]
Your PR contains a password that looks like it was copy pasted by accident, you might wanna remove it then make a new PR.

**Comment by pnomolos** [comment]
@svk31 Oh great, I'll get that done right away :cry:

**Comment by pnomolos** [comment]
Ah, it's the password for my testnet account so I don't care (uniquely generated).  I'll just over-write and force-push the commits, if that's OK?  If not I can open a new PR.

**Comment by pnomolos** [comment]
@svk31 OK I've mangled my way through this (merging on html with altered indent levels is a terrible experience).  Apart from a brief flash of the Send modal after a successful Send, I think this is actually pretty close to what would be optimal?

**Comment by pnomolos** [comment]
This is now smooth all the way through, but I'd like to get @svk31 thoughts as I changed the code in https://github.com/bitshares/bitshares-ui/pull/962/commits/b52e2f9a4b18ff8db62f2eb22c6a1efe99af5370 that was previously committed.  I'm not sure if there was a reason for making sure both the current state and next state for the component being marked as `open` as opposed to just the next state.

**Comment by svk31** [comment]
I commented on the reasoning for that in the commit above. Your change reintroduced the state bug that was preventing users from clicking send when opening the modal a second time after first making a transfer. I've restored the shouldComponentUpdate logic and fixed the flash by adding a condition to the "hide" class.

**Pull request merged**
